project:
  type: website
  #output-dir: _site
website:
  title: "ISSS626-yiqiong-pan"
  navbar:
    #background: "#dafad4"
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "01-1 Geospatial Data Science with R"
            href: "Hands-on_Ex/Hands-on_Ex01_1/Hands-on_Ex01_1.html"
          - text: "01-2 Thematic Mapping and GeoVisualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex01_2/Hands-on_Ex01_2.html"
          - text: "02-1: First-order Spatial Point Patterns Analysis Methods"
            href: "Hands-on_Ex/Hands-on_Ex02_1/Hands-on_Ex02_1.html"
          - text: "02-2: 2nd Order Spatial Point Patterns Analysis Methods"
            href: "Hands-on_Ex/Hands-on_Ex02_2/Hands-on_Ex02_2.html"            
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1"
          - text: "In-class Exercise 2"
      - text: "Take-home Exercise"
        menu: 
          - text: "Take-home Exercise 1"
          - text: "Take-home Exercise 2"
    right: 
      - href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/lsrgc
        aria-label: Github
      - icon: eyeglasses
        href: https://isss626-ay2025-26aug.netlify.app/
        aria-label: Course Textbook


format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
