project:
  type: website

website:
  title: "ISSS626-yiqiong-pan"
  navbar:
    left:
      - text: "Hands-on Exercise"
      - menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on Exercise/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
      - text: "In-class Exercise"
      - menu: 
        - text: "In-class Exercise 1"
        - text: "In-class Exercise 2"
    right: 
      -  href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

