project:
  type: website
  #output-dir: _site
website:
  title: "ISSS626-yiqiong-pan"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "01-1 Geospatial Data Science with R"
            href: "Hands-on_Ex/Hands-on_Ex01_1/Hands-on_Ex01_1.html"
          - text: "01-2 Thematic Mapping and GeoVisualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex01_2/Hands-on_Ex01_2.html"
          - text: "02-1: First-order Spatial Point Patterns Analysis Methods"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02_1.html"
          - text: "02-2: 2nd Order Spatial Point Patterns Analysis Methods"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02_2.html"            
          - text: "03: Spatio-Temporal Point Patterns Analysis"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "04: Spatial Weights and Applications"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"           
          - text: "05-1: Global Measures of Spatial Autocorrelation"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05-1.html"          
          - text: "05-2: Local Measures of Spatial Autocorrelation"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05-2.html"
          - text: "06: Geographical Segmentation with Spatially Constrained Clustering Techniques"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "07: Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
          - text: "08:"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
          - text: "09:"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"           
          - text: "10-1:"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10-1.html"               
          - text: "10-2:"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10-2.html"   
            
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 1: Geospatial Data Science with R"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2: Spatial Point Patterns Analysis: spatstat methods"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 03a"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03a.html"
          - text: "In-class Exercise 03b"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03b.html"
          - text: "In-class Exercise 04"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise 05a"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05a.html"
          - text: "In-class Exercise 05b"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05b.html"
          - text: "In-class Exercise 06"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
          - text: "In-class Exercise 07"
            href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
          - text: "In-class Exercise 08"
            href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
          - text: "In-class Exercise 09"
            href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"
      - text: "Take-home Exercise"
        menu: 
          - text: "01: Geospatial Analytics for Public Good: Agglomeration in Play"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "02: Geospatial Analytics for Public Good: Urban mobility"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.qmd" 
          - text: "03:"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.qmd" 
    right: 
      - href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/lsrgc
        aria-label: Github
      - icon: eyeglasses
        href: https://isss626-ay2025-26aug.netlify.app/
        aria-label: Course Textbook


format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
