project:
  type: website
  output-dir: _site
website:
  title: "ISSS626-yiqiong-pan"
  navbar:
    left:
      - text: "Hands-on_instExercise"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1"
          - text: "In-class Exercise 2"
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
