{
  "hash": "811a0604471cf5dda87c8ebfe406b078",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"In-class 07: Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method\"\nauthor: \"Yiqiong PAN\"\ndate: \"Oct 18, 2025\"\ndate-modified: last-modified\n\nexecute:\n  echo: true    # display the code\n  eval: true    # run the code\n  message: false\n  warning: false\n  freeze: true  # do not re-render if nothing edited\n\nformat: \n  html:\n    toc: true\n    code-link: true\n\nnumber-sections: true\nnumber-depth: 4\n\neditor: visual\n---\n\n## Overview\n\nGeographically weighted regression (GWR) is a spatial statistical technique that models relationships between independent non-stationary variables ( both external and internal) and the point of interest (dependent variable). In this case study, we apply the GWR methods to build the [hedonic pricing](https://www.investopedia.com/terms/h/hedonicpricing.asp) which identifies the intrinsic and environmental factors that influence the resale prices of condominium in 2015. Hedonic Pricing, developed by economist Sherwin Rosen, requires statistical expertise and data collection. Despite its strengths, hedonic pricing may miss additional influences like taxes, regulations, or unrecognised environmental issues.\n\nHere the independent variables include structural (e.g. size, age, number of rooms etc.) and locational (e.g. distance to MRT, park etc) factors.\n\n## The Data\n\nThe following data sets will be used in this study.\n\n| Dataset | Description | Format |\n|------------------------|------------------------|------------------------|\n| MP14_SUBZONE_WEB_PL | URA Master Plan subzone boundary 2014 | shapefile  |\n| ondo_resale_2015.csv | Resale prices of condominium in 2015 and selected factors | csv |\n\n## **Getting Started**\n\nThere are **10** packages used in this exercise.\n\n-   Spatial data handling (sf, sfdep)\n\n-   Attribute data handling (tidyverse including readr, ggplot2 and dplyr)\n\n-   Choropleth mapping (tmap)\n\n-   OLS building and testing (olsrr)\n\n-   calibration on Geographically weighted regression models (GWmodel)\n\n-   Multivariate exploration & Visualisation (corrplot)\n\n| Package | Description |\n|------------------------------------|------------------------------------|\n| [olsrr](https://olsrr.rsquaredacademy.com/) | Builds OLS and performs diagnostics tests |\n| [GWmodel](https://cran.r-project.org/web/packages/GWmodel/index.html) | Calibrates geographical weighted family of models |\n| [corrplot](https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html) | Performs multivariate data visualisation and analysis |\n| [sf](https://r-spatial.github.io/sf/) | Handles importing, managing, and processing vector-based geospatial data |\n| [tidyverse](https://www.tidyverse.org/) | A collection of R packages for data wrangling and visualisation, including **readr**, **dplyr**, and **ggplot2**. |\n| [tmap](https://r-tmap.github.io/tmap/) | Creates cartographic quality static and interactive thematic (choropleth) maps. |\n| [ggpubr](https://rpkgs.datanovia.com/ggpubr/) | Provides some easy-to-use functions for creating and customising ‘ggplot2’- based publication ready plots. |\n| [gtsummary](https://www.danieldsjoberg.com/gtsummary/) | Provides an elegant and flexible way to create publication-ready analytical and summary tables . |\n| [performance](https://cran.r-project.org/web/packages/performance/index.html) | Provides assessment of regression models performance (e.g. r-squared) |\n| [RColorBrewer](https://cran.r-project.org/web/packages/RColorBrewer/index.html) | Provides color schemes for maps (and other graphics) designed by Cynthia Brewer. |\n| [sfdep](https://sfdep.josiahparry.com/) | built on **spdep** provides a tidyverse-friendly interface with list-columns and additional functionality. **spdep** provides tools for spatial dependence: building neighbour lists, spatial weights, and spatial autocorrelation analysis. |\n\n: {tbl-colwidths=\"\\[15,85\\]\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(olsrr, corrplot, ggpubr, sf, sfdep, GWmodel, tmap, tidyverse,gtsummary, performance,RColorBrewer )\n```\n:::\n\n\n## A Short Note about GWmodel\n\n[GWmodel](https://www.jstatsoft.org/article/view/v063i17) provides a collection of localised spatial statistical methods, such as:\n\n-   GW summary statistics: shows how summary numbers (like mean or median) change from place to place.\n\n-   GW principal components analysis (PCA): finds patterns in data that may differ across regions.\n\n-   GW discriminant analysis: helps classify or group areas based on local patterns.\n\n-   Various forms of GW regression: explores how relationships between variables change by location.\n\nMany of these methods come in both basic and robust versions (the robust ones handle outliers better).\n\nThe results or parameters from GWmodel are often **mapped** to show how patterns vary across space. This mapping makes GWmodel a powerful **exploratory** tool that helps guide further, deeper statistical analysis.\n\n## Geospatial Data Wrangling\n\n### Importing Geospatial Data Using Functions from sf Package\n\nThe code chunk below imports `MP14_SUBZONE_WEB_PL` in ESRI shapefile format as **sf** polygon features to represent the geographic boundaries of the URA Master Plan 2014's planning subzones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz = st_read(dsn = \"data/geospatial\", layer= \"MP14_SUBZONE_WEB_PL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_WEB_PL' from data source \n  `C:\\lsrgc\\ISSS626-yiqiong-pan\\In-class_Ex\\In-class_Ex07\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\n```\n\n\n:::\n\n```{.r .cell-code}\nmpsz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\nFirst 10 features:\n   OBJECTID SUBZONE_NO       SUBZONE_N SUBZONE_C CA_IND      PLN_AREA_N\n1         1          1    MARINA SOUTH    MSSZ01      Y    MARINA SOUTH\n2         2          1    PEARL'S HILL    OTSZ01      Y          OUTRAM\n3         3          3       BOAT QUAY    SRSZ03      Y SINGAPORE RIVER\n4         4          8  HENDERSON HILL    BMSZ08      N     BUKIT MERAH\n5         5          3         REDHILL    BMSZ03      N     BUKIT MERAH\n6         6          7  ALEXANDRA HILL    BMSZ07      N     BUKIT MERAH\n7         7          9   BUKIT HO SWEE    BMSZ09      N     BUKIT MERAH\n8         8          2     CLARKE QUAY    SRSZ02      Y SINGAPORE RIVER\n9         9         13 PASIR PANJANG 1    QTSZ13      N      QUEENSTOWN\n10       10          7       QUEENSWAY    QTSZ07      N      QUEENSTOWN\n   PLN_AREA_C       REGION_N REGION_C          INC_CRC FMEL_UPD_D   X_ADDR\n1          MS CENTRAL REGION       CR 5ED7EB253F99252E 2014-12-05 31595.84\n2          OT CENTRAL REGION       CR 8C7149B9EB32EEFC 2014-12-05 28679.06\n3          SR CENTRAL REGION       CR C35FEFF02B13E0E5 2014-12-05 29654.96\n4          BM CENTRAL REGION       CR 3775D82C5DDBEFBD 2014-12-05 26782.83\n5          BM CENTRAL REGION       CR 85D9ABEF0A40678F 2014-12-05 26201.96\n6          BM CENTRAL REGION       CR 9D286521EF5E3B59 2014-12-05 25358.82\n7          BM CENTRAL REGION       CR 7839A8577144EFE2 2014-12-05 27680.06\n8          SR CENTRAL REGION       CR 48661DC0FBA09F7A 2014-12-05 29253.21\n9          QT CENTRAL REGION       CR 1F721290C421BFAB 2014-12-05 22077.34\n10         QT CENTRAL REGION       CR 3580D2AFFBEE914C 2014-12-05 24168.31\n     Y_ADDR SHAPE_Leng SHAPE_Area                       geometry\n1  29220.19   5267.381  1630379.3 MULTIPOLYGON (((31495.56 30...\n2  29782.05   3506.107   559816.2 MULTIPOLYGON (((29092.28 30...\n3  29974.66   1740.926   160807.5 MULTIPOLYGON (((29932.33 29...\n4  29933.77   3313.625   595428.9 MULTIPOLYGON (((27131.28 30...\n5  30005.70   2825.594   387429.4 MULTIPOLYGON (((26451.03 30...\n6  29991.38   4428.913  1030378.8 MULTIPOLYGON (((25899.7 297...\n7  30230.86   3275.312   551732.0 MULTIPOLYGON (((27746.95 30...\n8  30222.86   2208.619   290184.7 MULTIPOLYGON (((29351.26 29...\n9  29893.78   6571.323  1084792.3 MULTIPOLYGON (((20996.49 30...\n10 30104.18   3454.239   631644.3 MULTIPOLYGON (((24472.11 29...\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(mpsz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: SVY21 \n  wkt:\nPROJCRS[\"SVY21\",\n    BASEGEOGCRS[\"SVY21[WGS84]\",\n        DATUM[\"World Geodetic System 1984\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ID[\"EPSG\",6326]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"Degree\",0.0174532925199433]]],\n    CONVERSION[\"unnamed\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"Degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"Degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1,\n                ID[\"EPSG\",9001]]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1,\n                ID[\"EPSG\",9001]]]]\n```\n\n\n:::\n:::\n\n\nThe report shows the imported file `mpsz` is a simple feature collection with 323 **Multipolygon** features and 15 fields. The GIS data is in the projected coordinates system SVY21. However, the EPSG information is missing. Some agencies (like URA or data.gov.sg) don’t include the EPSG code explicitly in the `.prj` file that comes with a shapefile.\n\n### Updating CRS Information\n\nThe code chunk below uses st_transform() to assign appropriate EPSG 3414 to the file. The projected CRS is now \"SVY21 / Singapore TM\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_svy21 <- st_transform(mpsz, 3414)\nmpsz_svy21\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21 / Singapore TM\nFirst 10 features:\n   OBJECTID SUBZONE_NO       SUBZONE_N SUBZONE_C CA_IND      PLN_AREA_N\n1         1          1    MARINA SOUTH    MSSZ01      Y    MARINA SOUTH\n2         2          1    PEARL'S HILL    OTSZ01      Y          OUTRAM\n3         3          3       BOAT QUAY    SRSZ03      Y SINGAPORE RIVER\n4         4          8  HENDERSON HILL    BMSZ08      N     BUKIT MERAH\n5         5          3         REDHILL    BMSZ03      N     BUKIT MERAH\n6         6          7  ALEXANDRA HILL    BMSZ07      N     BUKIT MERAH\n7         7          9   BUKIT HO SWEE    BMSZ09      N     BUKIT MERAH\n8         8          2     CLARKE QUAY    SRSZ02      Y SINGAPORE RIVER\n9         9         13 PASIR PANJANG 1    QTSZ13      N      QUEENSTOWN\n10       10          7       QUEENSWAY    QTSZ07      N      QUEENSTOWN\n   PLN_AREA_C       REGION_N REGION_C          INC_CRC FMEL_UPD_D   X_ADDR\n1          MS CENTRAL REGION       CR 5ED7EB253F99252E 2014-12-05 31595.84\n2          OT CENTRAL REGION       CR 8C7149B9EB32EEFC 2014-12-05 28679.06\n3          SR CENTRAL REGION       CR C35FEFF02B13E0E5 2014-12-05 29654.96\n4          BM CENTRAL REGION       CR 3775D82C5DDBEFBD 2014-12-05 26782.83\n5          BM CENTRAL REGION       CR 85D9ABEF0A40678F 2014-12-05 26201.96\n6          BM CENTRAL REGION       CR 9D286521EF5E3B59 2014-12-05 25358.82\n7          BM CENTRAL REGION       CR 7839A8577144EFE2 2014-12-05 27680.06\n8          SR CENTRAL REGION       CR 48661DC0FBA09F7A 2014-12-05 29253.21\n9          QT CENTRAL REGION       CR 1F721290C421BFAB 2014-12-05 22077.34\n10         QT CENTRAL REGION       CR 3580D2AFFBEE914C 2014-12-05 24168.31\n     Y_ADDR SHAPE_Leng SHAPE_Area                       geometry\n1  29220.19   5267.381  1630379.3 MULTIPOLYGON (((31495.56 30...\n2  29782.05   3506.107   559816.2 MULTIPOLYGON (((29092.28 30...\n3  29974.66   1740.926   160807.5 MULTIPOLYGON (((29932.33 29...\n4  29933.77   3313.625   595428.9 MULTIPOLYGON (((27131.28 30...\n5  30005.70   2825.594   387429.4 MULTIPOLYGON (((26451.03 30...\n6  29991.38   4428.913  1030378.8 MULTIPOLYGON (((25899.7 297...\n7  30230.86   3275.312   551732.0 MULTIPOLYGON (((27746.95 30...\n8  30222.86   2208.619   290184.7 MULTIPOLYGON (((29351.26 29...\n9  29893.78   6571.323  1084792.3 MULTIPOLYGON (((20996.49 30...\n10 30104.18   3454.239   631644.3 MULTIPOLYGON (((24472.11 29...\n```\n\n\n:::\n:::\n\n\nThe code chunk below checks the CRS code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(mpsz_svy21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n\nThe code chunk reveals the extent of **mpsz_svy21** by using `st_bbox()` of sf pacakge by its lower and upper limits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_bbox(mpsz_svy21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     xmin      ymin      xmax      ymax \n 2667.538 15748.721 56396.440 50256.334 \n```\n\n\n:::\n:::\n\n\n## Aspatial Data Wrangling Using Functions from tidyverse and sf Packages\n\nThe code chunk below uses `read_csv()` from **readr** to import the csv file *condo_resale_2015* into R as tibble data frame and names it *condo_resale*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale = read_csv(\"data/aspatial/condo_resale_2015.csv\")\n```\n:::\n\n\nWe use `glimpse()` to have a quick look at the data structure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(condo_resale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,436\nColumns: 23\n$ LATITUDE             <dbl> 1.287145, 1.328698, 1.313727, 1.308563, 1.321437,…\n$ LONGITUDE            <dbl> 103.7802, 103.8123, 103.7971, 103.8247, 103.9505,…\n$ POSTCODE             <dbl> 118635, 288420, 267833, 258380, 467169, 466472, 3…\n$ SELLING_PRICE        <dbl> 3000000, 3880000, 3325000, 4250000, 1400000, 1320…\n$ AREA_SQM             <dbl> 309, 290, 248, 127, 145, 139, 218, 141, 165, 168,…\n$ AGE                  <dbl> 30, 32, 33, 7, 28, 22, 24, 24, 27, 31, 17, 22, 6,…\n$ PROX_CBD             <dbl> 7.941259, 6.609797, 6.898000, 4.038861, 11.783402…\n$ PROX_CHILDCARE       <dbl> 0.16597932, 0.28027246, 0.42922669, 0.39473543, 0…\n$ PROX_ELDERLYCARE     <dbl> 2.5198118, 1.9333338, 0.5021395, 1.9910316, 1.121…\n$ PROX_URA_GROWTH_AREA <dbl> 6.618741, 7.505109, 6.463887, 4.906512, 6.410632,…\n$ PROX_HAWKER_MARKET   <dbl> 1.76542207, 0.54507614, 0.37789301, 1.68259969, 0…\n$ PROX_KINDERGARTEN    <dbl> 0.05835552, 0.61592412, 0.14120309, 0.38200076, 0…\n$ PROX_MRT             <dbl> 0.5607188, 0.6584461, 0.3053433, 0.6910183, 0.528…\n$ PROX_PARK            <dbl> 1.1710446, 0.1992269, 0.2779886, 0.9832843, 0.116…\n$ PROX_PRIMARY_SCH     <dbl> 1.6340256, 0.9747834, 1.4715016, 1.4546324, 0.709…\n$ PROX_TOP_PRIMARY_SCH <dbl> 3.3273195, 0.9747834, 1.4715016, 2.3006394, 0.709…\n$ PROX_SHOPPING_MALL   <dbl> 2.2102717, 2.9374279, 1.2256850, 0.3525671, 1.307…\n$ PROX_SUPERMARKET     <dbl> 0.9103958, 0.5900617, 0.4135583, 0.4162219, 0.581…\n$ PROX_BUS_STOP        <dbl> 0.10336166, 0.28673408, 0.28504777, 0.29872340, 0…\n$ NO_Of_UNITS          <dbl> 18, 20, 27, 30, 30, 31, 32, 32, 32, 32, 34, 34, 3…\n$ FAMILY_FRIENDLY      <dbl> 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0…\n$ FREEHOLD             <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1…\n$ LEASEHOLD_99YR       <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(condo_resale$LONGITUDE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 103.7802 103.8123 103.7971 103.8247 103.9505 103.9386\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(condo_resale$LATITUDE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.287145 1.328698 1.313727 1.308563 1.321437 1.314198\n```\n\n\n:::\n:::\n\n\nThe code chunk above displays the Longitude and Latitude values of first 5 rows. Since they are probably in WGS84 with decimal degree, transformation is necessary.\n\nThe code chunk below reveals the summary statistics for each field.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(condo_resale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    LATITUDE       LONGITUDE        POSTCODE      SELLING_PRICE     \n Min.   :1.240   Min.   :103.7   Min.   : 18965   Min.   :  540000  \n 1st Qu.:1.309   1st Qu.:103.8   1st Qu.:259849   1st Qu.: 1100000  \n Median :1.328   Median :103.8   Median :469298   Median : 1383222  \n Mean   :1.334   Mean   :103.8   Mean   :440439   Mean   : 1751211  \n 3rd Qu.:1.357   3rd Qu.:103.9   3rd Qu.:589486   3rd Qu.: 1950000  \n Max.   :1.454   Max.   :104.0   Max.   :828833   Max.   :18000000  \n    AREA_SQM          AGE           PROX_CBD       PROX_CHILDCARE    \n Min.   : 34.0   Min.   : 0.00   Min.   : 0.3869   Min.   :0.004927  \n 1st Qu.:103.0   1st Qu.: 5.00   1st Qu.: 5.5574   1st Qu.:0.174481  \n Median :121.0   Median :11.00   Median : 9.3567   Median :0.258135  \n Mean   :136.5   Mean   :12.14   Mean   : 9.3254   Mean   :0.326313  \n 3rd Qu.:156.0   3rd Qu.:18.00   3rd Qu.:12.6661   3rd Qu.:0.368293  \n Max.   :619.0   Max.   :37.00   Max.   :19.1804   Max.   :3.465726  \n PROX_ELDERLYCARE  PROX_URA_GROWTH_AREA PROX_HAWKER_MARKET PROX_KINDERGARTEN \n Min.   :0.05451   Min.   :0.2145       Min.   :0.05182    Min.   :0.004927  \n 1st Qu.:0.61254   1st Qu.:3.1643       1st Qu.:0.55245    1st Qu.:0.276345  \n Median :0.94179   Median :4.6186       Median :0.90842    Median :0.413385  \n Mean   :1.05352   Mean   :4.5981       Mean   :1.27987    Mean   :0.458903  \n 3rd Qu.:1.35122   3rd Qu.:5.7550       3rd Qu.:1.68578    3rd Qu.:0.578474  \n Max.   :3.94916   Max.   :9.1554       Max.   :5.37435    Max.   :2.229045  \n    PROX_MRT         PROX_PARK       PROX_PRIMARY_SCH  PROX_TOP_PRIMARY_SCH\n Min.   :0.05278   Min.   :0.02906   Min.   :0.07711   Min.   :0.07711     \n 1st Qu.:0.34646   1st Qu.:0.26211   1st Qu.:0.44024   1st Qu.:1.34451     \n Median :0.57430   Median :0.39926   Median :0.63505   Median :1.88213     \n Mean   :0.67316   Mean   :0.49802   Mean   :0.75471   Mean   :2.27347     \n 3rd Qu.:0.84844   3rd Qu.:0.65592   3rd Qu.:0.95104   3rd Qu.:2.90954     \n Max.   :3.48037   Max.   :2.16105   Max.   :3.92899   Max.   :6.74819     \n PROX_SHOPPING_MALL PROX_SUPERMARKET PROX_BUS_STOP       NO_Of_UNITS    \n Min.   :0.0000     Min.   :0.0000   Min.   :0.001595   Min.   :  18.0  \n 1st Qu.:0.5258     1st Qu.:0.3695   1st Qu.:0.098356   1st Qu.: 188.8  \n Median :0.9357     Median :0.5687   Median :0.151711   Median : 360.0  \n Mean   :1.0455     Mean   :0.6141   Mean   :0.193974   Mean   : 409.2  \n 3rd Qu.:1.3994     3rd Qu.:0.7862   3rd Qu.:0.220466   3rd Qu.: 590.0  \n Max.   :3.4774     Max.   :2.2441   Max.   :2.476639   Max.   :1703.0  \n FAMILY_FRIENDLY     FREEHOLD      LEASEHOLD_99YR  \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :0.0000   Median :0.0000   Median :0.0000  \n Mean   :0.4868   Mean   :0.4227   Mean   :0.4882  \n 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n```\n\n\n:::\n:::\n\n\n### Converting Aspatial Data Frame into a sf Object\n\nThe code chunk below converts condo_resale data frame into a simple feature data frame by using st_as_sf() of sf packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf <- st_as_sf(condo_resale, coords = c(\"LONGITUDE\", \"LATITUDE\"),\n                            crs = 4326) %>%\n  st_transform(crs = 3414)  # converts wgs84 (4326) to svy21 (3414)\n```\n:::\n\n\nWe have a quick overview on the transformed sf data frame. The output is in point feature data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(condo_resale.sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 21 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 22085.12 ymin: 29951.54 xmax: 41042.56 ymax: 34546.2\nProjected CRS: SVY21 / Singapore TM\n# A tibble: 6 × 22\n  POSTCODE SELLING_PRICE AREA_SQM   AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE\n     <dbl>         <dbl>    <dbl> <dbl>    <dbl>          <dbl>            <dbl>\n1   118635       3000000      309    30     7.94          0.166            2.52 \n2   288420       3880000      290    32     6.61          0.280            1.93 \n3   267833       3325000      248    33     6.90          0.429            0.502\n4   258380       4250000      127     7     4.04          0.395            1.99 \n5   467169       1400000      145    28    11.8           0.119            1.12 \n6   466472       1320000      139    22    10.3           0.125            0.789\n# ℹ 15 more variables: PROX_URA_GROWTH_AREA <dbl>, PROX_HAWKER_MARKET <dbl>,\n#   PROX_KINDERGARTEN <dbl>, PROX_MRT <dbl>, PROX_PARK <dbl>,\n#   PROX_PRIMARY_SCH <dbl>, PROX_TOP_PRIMARY_SCH <dbl>,\n#   PROX_SHOPPING_MALL <dbl>, PROX_SUPERMARKET <dbl>, PROX_BUS_STOP <dbl>,\n#   NO_Of_UNITS <dbl>, FAMILY_FRIENDLY <dbl>, FREEHOLD <dbl>,\n#   LEASEHOLD_99YR <dbl>, geometry <POINT [m]>\n```\n\n\n:::\n:::\n\n\n## Exploratory Data Analysis (EDA) Using Functions from ggplot2 Package\n\nIn this section, we perform EDA using statistical graphics functions of **ggplot2** package.\n\n### EDA using Statistical Praphics\n\nThe code chunk below creates the histogram for distribution of SELLING_PRICE by using `geom_histogram()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = condo_resale.sf, aes (x = `SELLING_PRICE`)) +\n  geom_histogram(bins = 20, color = \"black\", fill = \"light blue\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nThe histogram shows that the distribution of selling prices is right-skewed, meaning that most condominiums were sold at relatively lower price ranges.\n\nA skewed distribution can be normalised using a **log transformation**.\n\nThe code chunk below creates a new variable called *LOG_SELLING_PRICE* by applying a log transformation to the variable *SELLING_PRICE*. This transformation is performed using the mutate() from the dplyr package and log() from base R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf <- condo_resale.sf %>%\n  mutate(`LOG_SELLING_PRICE` = log(SELLING_PRICE))\n```\n:::\n\n\nThe code chunk plots the LOG_SELLING_PRICE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = condo_resale.sf, aes (x = `LOG_SELLING_PRICE`)) +\n  geom_histogram(bins = 20, color = \"black\", fill = \"light blue\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThe distribution becomes less skewed after the transformation.\n\n### Multiple Histogram Plots Distribution of Variables\n\nIn this section, we create function to draw trellis plots (multiple histograms) for independent variables and arrange them into a grid of 4 rows and 3 columns by using `ggarrange()` from [**ggpubr**](https://cran.r-project.org/web/packages/ggpubr/index.html) package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# <- ggplot(data = condo_resale.sf, aes(x = AREA_SQM)) +\n  #geom_histogram(bins = 20,\n                 #color = \"black\",\n                 #fill = \"light blue\")\n\n#ggarrange(AREA_SQM, ncol = 3, nrow = 4)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncols <- names(condo_resale.sf)[3:21]\nplot_list <- lapply(cols, function(var) {\n  ggplot(condo_resale.sf, aes(x = .data[[var]])) +\n    geom_histogram(bins = 20, color = \"black\", fill = \"light blue\") \n})\nggarrange(plotlist = plot_list, ncol = 3, nrow = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`1`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n$`2`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nattr(,\"class\")\n[1] \"list\"      \"ggarrange\"\n```\n\n\n:::\n:::\n\n\n### Drawing Statistical Point Map Using Functions from tmap Package\n\nThe code chunk below displays the geospatial distribution of condominium resale prices in Singapore in an interactive point symbol map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_svy21) +         #base multipolygons\n  tm_polygons() +\ntm_shape(condo_resale.sf) +    #event points\n  tm_dots(fill = \"SELLING_PRICE\",\n          fill_alpha = 0.6,\n          size = 0.5,\n          fill.scale = tm_scale_intervals(\n            style = \"quantile\" )) +\n  tm_view(set_zoom_limits = c(11,14)) #focused view\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n[`tm_dots()`](https://www.rdocumentation.org/packages/tmap/versions/2.2/topics/tm_symbols) is used instead of tm_bubbles().\n\n`set_zoom_limits` argument of `tm_view()` sets the minimum and maximum zoom level to 11 and 14 respectively.\n\nBefore moving to next section, we reset the plot mode to static.\n\n## Hedonic Pricing Modelling Using Functions from Base R\n\nNext we build the hedonic pricing models for condominium reale units using [`lm()`](https://www.rdocumentation.org/packages/stats/versions/3.5.2/topics/lm) of base R.\n\n::: callout-note\n-   syntax:\n\nlm(formula, data, subset, weights, na.action, method = \"qr\", model = TRUE, x = FALSE, y = FALSE, qr = TRUE, singular.ok = TRUE, contrasts = NULL, offset, …)\n:::\n\n### Simple Linear Regression Method\n\nFirst, the code chunk below build a simple linear regression model that predicts **SELLING_PRICE** based on **AREA_SQM**.The **tilde (\\~)** is read as “is modelled by” or “as a function of.”\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.slr <-lm(formula = SELLING_PRICE ~ AREA_SQM, data = condo_resale.sf)\n```\n:::\n\n\nThe code chunk blow prints the model call from R's lm() linear model function and model's coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.slr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = SELLING_PRICE ~ AREA_SQM, data = condo_resale.sf)\n\nCoefficients:\n(Intercept)     AREA_SQM  \n    -258121        14719  \n```\n\n\n:::\n:::\n\n\nThe code chunk below returns the summary report of the simple regression model.\n\n1.  Residuals rules:\n\n| Residuals Statistic | Interpretation           |\n|---------------------|--------------------------|\n| Median approx 0     | unbiased model overall   |\n| Negative median     | Overestimate on average  |\n| Positive median     | Underestimate on average |\n\nSince the median is negative -87K, the model slightly overestimates the selling prices.\n\n2.  Coefficients:\n\nThe linear relationship can be described as:\n\nSELLING_PRICE = -258121.1 + 14719.0 x AREA_SQM\n\nThat means every one sqm increases in area will result in \\$14,719 increases in selling price on average. Since selling price is not below zero in real life, the intercept has no practical meaning. Since p-values of coefficients are much smaller than 0.001,we reject the null hypothesis that both coefficient are statistically significant.\n\n3.  Model fit Statistics\n\nResidual standard error of 942,700 means that the predictions are about \\$942,700 away from the actual prices on average. The R-squared 0.4518 means the simple linear model can explain 45% of variance in resale prices. The p-value of F-statistics (\\< 0.001) confirms that the simple model is statistically significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(condo.slr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = SELLING_PRICE ~ AREA_SQM, data = condo_resale.sf)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-3695815  -391764   -87517   258900 13503875 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -258121.1    63517.2  -4.064 5.09e-05 ***\nAREA_SQM      14719.0      428.1  34.381  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 942700 on 1434 degrees of freedom\nMultiple R-squared:  0.4518,\tAdjusted R-squared:  0.4515 \nF-statistic:  1182 on 1 and 1434 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe code chunk below reveals the internal structure of the regression model, displaying a compact list of its components, class, and dimensions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(condo.slr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 12\n $ coefficients : Named num [1:2] -258121 14719\n  ..- attr(*, \"names\")= chr [1:2] \"(Intercept)\" \"AREA_SQM\"\n $ residuals    : Named num [1:1436] -1290059 -130397 -67198 2638804 -476138 ...\n  ..- attr(*, \"names\")= chr [1:1436] \"1\" \"2\" \"3\" \"4\" ...\n $ effects      : Named num [1:1436] -66361417 -32409518 -29602 2671396 -442802 ...\n  ..- attr(*, \"names\")= chr [1:1436] \"(Intercept)\" \"AREA_SQM\" \"\" \"\" ...\n $ rank         : int 2\n $ fitted.values: Named num [1:1436] 4290059 4010397 3392198 1611196 1876138 ...\n  ..- attr(*, \"names\")= chr [1:1436] \"1\" \"2\" \"3\" \"4\" ...\n $ assign       : int [1:2] 0 1\n $ qr           :List of 5\n  ..$ qr   : num [1:1436, 1:2] -37.8946 0.0264 0.0264 0.0264 0.0264 ...\n  .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. ..$ : chr [1:1436] \"1\" \"2\" \"3\" \"4\" ...\n  .. .. ..$ : chr [1:2] \"(Intercept)\" \"AREA_SQM\"\n  .. ..- attr(*, \"assign\")= int [1:2] 0 1\n  ..$ qraux: num [1:2] 1.03 1.07\n  ..$ pivot: int [1:2] 1 2\n  ..$ tol  : num 1e-07\n  ..$ rank : int 2\n  ..- attr(*, \"class\")= chr \"qr\"\n $ df.residual  : int 1434\n $ xlevels      : Named list()\n $ call         : language lm(formula = SELLING_PRICE ~ AREA_SQM, data = condo_resale.sf)\n $ terms        :Classes 'terms', 'formula'  language SELLING_PRICE ~ AREA_SQM\n  .. ..- attr(*, \"variables\")= language list(SELLING_PRICE, AREA_SQM)\n  .. ..- attr(*, \"factors\")= int [1:2, 1] 0 1\n  .. .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. .. ..$ : chr [1:2] \"SELLING_PRICE\" \"AREA_SQM\"\n  .. .. .. ..$ : chr \"AREA_SQM\"\n  .. ..- attr(*, \"term.labels\")= chr \"AREA_SQM\"\n  .. ..- attr(*, \"order\")= int 1\n  .. ..- attr(*, \"intercept\")= int 1\n  .. ..- attr(*, \"response\")= int 1\n  .. ..- attr(*, \".Environment\")=<environment: R_GlobalEnv> \n  .. ..- attr(*, \"predvars\")= language list(SELLING_PRICE, AREA_SQM)\n  .. ..- attr(*, \"dataClasses\")= Named chr [1:2] \"numeric\" \"numeric\"\n  .. .. ..- attr(*, \"names\")= chr [1:2] \"SELLING_PRICE\" \"AREA_SQM\"\n $ model        :'data.frame':\t1436 obs. of  2 variables:\n  ..$ SELLING_PRICE: num [1:1436] 3000000 3880000 3325000 4250000 1400000 ...\n  ..$ AREA_SQM     : num [1:1436] 309 290 248 127 145 139 218 141 165 168 ...\n  ..- attr(*, \"terms\")=Classes 'terms', 'formula'  language SELLING_PRICE ~ AREA_SQM\n  .. .. ..- attr(*, \"variables\")= language list(SELLING_PRICE, AREA_SQM)\n  .. .. ..- attr(*, \"factors\")= int [1:2, 1] 0 1\n  .. .. .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. .. .. ..$ : chr [1:2] \"SELLING_PRICE\" \"AREA_SQM\"\n  .. .. .. .. ..$ : chr \"AREA_SQM\"\n  .. .. ..- attr(*, \"term.labels\")= chr \"AREA_SQM\"\n  .. .. ..- attr(*, \"order\")= int 1\n  .. .. ..- attr(*, \"intercept\")= int 1\n  .. .. ..- attr(*, \"response\")= int 1\n  .. .. ..- attr(*, \".Environment\")=<environment: R_GlobalEnv> \n  .. .. ..- attr(*, \"predvars\")= language list(SELLING_PRICE, AREA_SQM)\n  .. .. ..- attr(*, \"dataClasses\")= Named chr [1:2] \"numeric\" \"numeric\"\n  .. .. .. ..- attr(*, \"names\")= chr [1:2] \"SELLING_PRICE\" \"AREA_SQM\"\n - attr(*, \"class\")= chr \"lm\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(condo.slr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"lm\"\n```\n\n\n:::\n:::\n\n\nWe can also use **\\$** symbol to access important elements of the model (such as coefficients, effects, fitted.values and residuals) from the list output revealed by the `str()` structure function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.slr$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)    AREA_SQM \n -258121.06    14719.03 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.slr$effects\n```\n:::\n\n\nThe code chunk below visualises the simple linear model using functions from **ggplot2**. geom_smooth(method = lm) adds a linear regression line to the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = condo_resale.sf,\n       aes (x=`AREA_SQM`, y = `SELLING_PRICE`)) +\n  geom_point()+   # shows the scatter plot of area_sqm and selling price\n  geom_smooth(method = lm)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nWe observe a few outliers with relatively high selling prices.\n\n### Multiple Linear Regression Method Using Functions from corrplot and Base R\n\n#### Visualising the relationships of the independent variables\n\nBefore building the multiple linear regression model, we need to check for **multicollinearity** that independent variables are not highly correlated with each other. Otherwise, there will be redundancy in the model, which can distort the estimated effects of the predictors.\n\nThe code chunk below plot the correlation matrix of the independent variables. The [**corrplot**](https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html) package is used because the `pairs()` from base R output can be cramped and difficult to interpret when there are many variables. The data set used is not the converted sf object but our regular data frame because most statistical plotting functions cannot handle spatial geometry columns. AOE order is used, as recommended by [Michael Friendly](https://www.datavis.ca/papers/corrgram.pdf).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrplot(cor(condo_resale[, 5:23]), \n         diag = FALSE, # hide diagonal or TRUE\n         order = \"AOE\", # angular order of the eigenvectors\" /original/AOE/FPC/hclust/alphabet\n         tl.pos = \"td\", # text label position: top and diagonal/lt/n null\n         tl.cex = 0.5,  # text label size: shrinks 50%\n         method = \"number\", # display number/circle/color/shade/pie\n         type = \"upper\") #show only the upper triangle/full/lower\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nThe output shows a triangular matrix of pairwise correlation values between variables.\n\n| Correlation r value | Interpretation         |\n|---------------------|------------------------|\n| (0,1)               | positive relationships |\n| =0                  | no correlation         |\n| (-1,0)              | negative relationships |\n\nVariables with high correlation values (\\|r\\| \\> 0.8) may indicate potential multicollinearity. They are **Freehold and LEASE_99YEAR**. We select **Freehold** from one of the pair.\n\n### Building a hedonic pricing model Using lm() from Base R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.mlr <- lm(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +\n    PROX_URA_GROWTH_AREA + PROX_HAWKER_MARKET   +\n    PROX_KINDERGARTEN   + PROX_MRT  + PROX_PARK +\n    PROX_PRIMARY_SCH + PROX_TOP_PRIMARY_SCH +\n    PROX_SHOPPING_MALL  + PROX_SUPERMARKET + \n    PROX_BUS_STOP   + NO_Of_UNITS + \n    FAMILY_FRIENDLY + FREEHOLD, \n  data=condo_resale.sf)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(condo.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + \n    PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + PROX_HAWKER_MARKET + \n    PROX_KINDERGARTEN + PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + \n    PROX_TOP_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_SUPERMARKET + \n    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, \n    data = condo_resale.sf)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-3475964  -293923   -23069   241043 12260381 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           481728.40  121441.01   3.967 7.65e-05 ***\nAREA_SQM               12708.32     369.59  34.385  < 2e-16 ***\nAGE                   -24440.82    2763.16  -8.845  < 2e-16 ***\nPROX_CBD              -78669.78    6768.97 -11.622  < 2e-16 ***\nPROX_CHILDCARE       -351617.91  109467.25  -3.212  0.00135 ** \nPROX_ELDERLYCARE      171029.42   42110.51   4.061 5.14e-05 ***\nPROX_URA_GROWTH_AREA   38474.53   12523.57   3.072  0.00217 ** \nPROX_HAWKER_MARKET     23746.10   29299.76   0.810  0.41782    \nPROX_KINDERGARTEN     147468.99   82668.87   1.784  0.07466 .  \nPROX_MRT             -314599.68   57947.44  -5.429 6.66e-08 ***\nPROX_PARK             563280.50   66551.68   8.464  < 2e-16 ***\nPROX_PRIMARY_SCH      180186.08   65237.95   2.762  0.00582 ** \nPROX_TOP_PRIMARY_SCH    2280.04   20410.43   0.112  0.91107    \nPROX_SHOPPING_MALL   -206604.06   42840.60  -4.823 1.57e-06 ***\nPROX_SUPERMARKET      -44991.80   77082.64  -0.584  0.55953    \nPROX_BUS_STOP         683121.35  138353.28   4.938 8.85e-07 ***\nNO_Of_UNITS             -231.18      89.03  -2.597  0.00951 ** \nFAMILY_FRIENDLY       140340.77   47020.55   2.985  0.00289 ** \nFREEHOLD              359913.01   49220.22   7.312 4.38e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 755800 on 1417 degrees of freedom\nMultiple R-squared:  0.6518,\tAdjusted R-squared:  0.6474 \nF-statistic: 147.4 on 18 and 1417 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe code chunk above returns the summary report of the multiple linear regression model.\n\n1.  Residuals:\n\nSince the median is negative -23K, the model slightly overestimates the selling prices but improved from the simple model.\n\n2.  Coefficients:\n\nIf the significance level alpha is set at 0.05, variables with p-values higher than 0.05 should be dropped from the model, as they are not statistically significant.Variables to drop are PROX_HAWKER_MARKET, PROX_KINDERGARTEN, PROX_TOP_PRIMARY_SCH and PROX_SUPERMARKET.\n\nThe predictors with p-values less than 0.05 are retained, since they show strong evidence of a relationship with the resale prices.\n\nThe linear relationship can be described as:\n\ne.g. that every one sqm increases in area will result in \\$12,708.32 increases in selling price on average.\n\nThe intercept 481,728 represents the baseline selling price when all variables are zero.\n\n3.  Model fit Statistics\n\nResidual standard error of 755,800 means that the predictions are about \\$755,800 away from the actual prices on average.\n\nThe p-value of F-statistics (\\< 0.001) confirms that the new model is statistically significant.\n\nThe R-squared value of 0.6518 indicates that the multiple linear regression model explains approximately 65% of the variance in condominium resale prices. Compared to the simple linear model (R2 = 0.45; adjusted R2 = 0.45), the multiple regression model (adjusted R2 = 0.6474) provides a more sophisticated and accurate representation of the factors influencing resale prices.\n\n### Revising the Model\n\nThe code chunk below builds a new multiple regression moedel with the variables deemed as statistically significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.mlr1 <- lm(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE + \n    PROX_CBD + PROX_CHILDCARE + PROX_MRT +\n    PROX_ELDERLYCARE    + PROX_URA_GROWTH_AREA +\n    PROX_PARK   + PROX_PRIMARY_SCH + \n    PROX_SHOPPING_MALL  + PROX_BUS_STOP + \n    NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD,\n  data=condo_resale.sf)\nsummary(condo.mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + \n    PROX_MRT + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + PROX_PARK + \n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_BUS_STOP + NO_Of_UNITS + \n    FAMILY_FRIENDLY + FREEHOLD, data = condo_resale.sf)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-3470778  -298119   -23481   248917 12234210 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           527633.22  108183.22   4.877 1.20e-06 ***\nAREA_SQM               12777.52     367.48  34.771  < 2e-16 ***\nAGE                   -24687.74    2754.84  -8.962  < 2e-16 ***\nPROX_CBD              -77131.32    5763.12 -13.384  < 2e-16 ***\nPROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** \nPROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***\nPROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***\nPROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***\nPROX_PARK             570504.81   65507.03   8.709  < 2e-16 ***\nPROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** \nPROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***\nPROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***\nNO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** \nFAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** \nFREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 756000 on 1421 degrees of freedom\nMultiple R-squared:  0.6507,\tAdjusted R-squared:  0.6472 \nF-statistic: 189.1 on 14 and 1421 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe report suggests all explanatory variables are statistically significant at 95% confident level.\n\n### Preparing Publication Quality Table: gtsummary Method\n\nThe code chunk below uses [`tbl_regression()`](https://www.danieldsjoberg.com/gtsummary/reference/tbl_regression.html) from [**gtsummary**](https://www.danieldsjoberg.com/gtsummary/index.html) package to create an elegant and well formatted regression summary table.\n\nMore statistical results can be included in the table via [`add_glance_table()`](https://www.danieldsjoberg.com/gtsummary/reference/add_glance.html) or [`add_glance_source_note()`](https://www.danieldsjoberg.com/gtsummary/reference/add_glance.html).\n\nRefer to the [tutorial](https://www.danieldsjoberg.com/gtsummary/articles/tbl_regression.html) for more details.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(condo.mlr1, intercept = TRUE) %>%\n  bold_labels() %>%\n  bold_p(t = 0.05) %>%\n  add_glance_source_note(\n    label = list(sigma~ \"\\U03C3\"),\n    include = c(r.squared, adj.r.squared, AIC, statistic, p.value, sigma)\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tnujeiiokq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tnujeiiokq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tnujeiiokq thead, #tnujeiiokq tbody, #tnujeiiokq tfoot, #tnujeiiokq tr, #tnujeiiokq td, #tnujeiiokq th {\n  border-style: none;\n}\n\n#tnujeiiokq p {\n  margin: 0;\n  padding: 0;\n}\n\n#tnujeiiokq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tnujeiiokq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tnujeiiokq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tnujeiiokq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tnujeiiokq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tnujeiiokq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tnujeiiokq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tnujeiiokq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tnujeiiokq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tnujeiiokq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tnujeiiokq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tnujeiiokq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tnujeiiokq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tnujeiiokq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tnujeiiokq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tnujeiiokq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tnujeiiokq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tnujeiiokq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tnujeiiokq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tnujeiiokq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tnujeiiokq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tnujeiiokq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tnujeiiokq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tnujeiiokq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tnujeiiokq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tnujeiiokq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tnujeiiokq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tnujeiiokq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tnujeiiokq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tnujeiiokq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tnujeiiokq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tnujeiiokq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tnujeiiokq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tnujeiiokq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tnujeiiokq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tnujeiiokq .gt_left {\n  text-align: left;\n}\n\n#tnujeiiokq .gt_center {\n  text-align: center;\n}\n\n#tnujeiiokq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tnujeiiokq .gt_font_normal {\n  font-weight: normal;\n}\n\n#tnujeiiokq .gt_font_bold {\n  font-weight: bold;\n}\n\n#tnujeiiokq .gt_font_italic {\n  font-style: italic;\n}\n\n#tnujeiiokq .gt_super {\n  font-size: 65%;\n}\n\n#tnujeiiokq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tnujeiiokq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tnujeiiokq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tnujeiiokq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tnujeiiokq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tnujeiiokq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tnujeiiokq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tnujeiiokq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tnujeiiokq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">527,633</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">315,417, 739,849</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">AREA_SQM</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">12,778</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">12,057, 13,498</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">AGE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-24,688</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-30,092, -19,284</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">PROX_CBD</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-77,131</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-88,436, -65,826</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">PROX_CHILDCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-318,473</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-530,250, -106,696</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">0.003</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">PROX_MRT</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-294,745</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-406,394, -183,096</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">PROX_ELDERLYCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">185,576</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">107,303, 263,849</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">PROX_URA_GROWTH_AREA</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">39,163</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">16,105, 62,222</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">PROX_PARK</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">570,505</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">442,004, 699,006</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">PROX_PRIMARY_SCH</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">159,856</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">41,698, 278,014</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">0.008</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">PROX_SHOPPING_MALL</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-220,947</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-292,668, -149,226</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">PROX_BUS_STOP</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">682,482</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">418,616, 946,348</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">NO_Of_UNITS</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-245</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-418, -73</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">0.005</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">FAMILY_FRIENDLY</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">146,308</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">54,321, 238,295</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">0.002</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">FREEHOLD</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">350,600</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">255,448, 445,752</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></span></td>\n    </tr>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"UsKyID0gMC42NTE7IEFkanVzdGVkIFLCsiA9IDAuNjQ3OyBBSUMgPSA0Miw5Njc7IFN0YXRpc3RpYyA9IDE4OTsgcC12YWx1ZSA9IDwwLjAwMTsgz4MgPSA3NTUsOTU3\"><span class='gt_from_md'>R² = 0.651; Adjusted R² = 0.647; AIC = 42,967; Statistic = 189; p-value = &lt;0.001; σ = 755,957</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nR2s have been explained earlier.\n\nAIC stands for Akaike Information Criterion which measures model quality by goodness of fit and complexity. The lower value means better model given same data.\n\nStatistic is F-statistic and its p-value. Sigma is Residual Standard Error.\n\nAll these metrics are reported in the model summary output via summary().\n\n### Regression Diagnostics\n\nRegression model’s assumptions are:\n\n-   Linearity: Predictors have linear relation to target\n-   Independence: Errors are independent\n-   Homoscedasticity: Constant variance of residuals, Residual plot\n-   Normality: Errors are normally distributed, QQ plot\n-   No Multicollinearity: Predictors not highly correlated\n\nIn this section, we use [**olsrr**](https://olsrr.rsquaredacademy.com/) package to perform the OLS regression diagnostics.\n\nThe olsrr package provides following tools for building OLS regression models using R:\n\n-   Comprehensive Regression Output\n-   Variable Selection Procedures\n-   Heteroskedasticity Tests\n-   Collinearity Diagnostics\n-   Model Fit Assessment\n-   Measures of Influence\n-   Residual Diagnostics\n-   Variable Contribution Assessment\n\n:::: panel-tabset\n#### Multicollinearity Test\n\n**Multicollinearity** occurs when independent variables are highly correlated. High multicollinearity inflates the variance of coefficient estimates, leading to unstable and unreliable results, and may cause truly important predictors to appear statistically insignificant.\n\nThe code chunk below use [`check_collinearity()`](https://easystats.github.io/performance/reference/check_collinearity.html) from **performance** package to test the Multicollinearity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_collinearity(condo.mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n                 Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n             AREA_SQM 1.15 [1.09, 1.23]     1.07      0.87     [0.81, 0.92]\n                  AGE 1.41 [1.33, 1.52]     1.19      0.71     [0.66, 0.75]\n             PROX_CBD 1.57 [1.47, 1.69]     1.25      0.64     [0.59, 0.68]\n       PROX_CHILDCARE 3.26 [3.00, 3.56]     1.81      0.31     [0.28, 0.33]\n             PROX_MRT 1.91 [1.78, 2.07]     1.38      0.52     [0.48, 0.56]\n     PROX_ELDERLYCARE 1.52 [1.42, 1.63]     1.23      0.66     [0.61, 0.70]\n PROX_URA_GROWTH_AREA 1.33 [1.26, 1.43]     1.15      0.75     [0.70, 0.80]\n            PROX_PARK 1.21 [1.15, 1.29]     1.10      0.83     [0.77, 0.87]\n     PROX_PRIMARY_SCH 2.21 [2.05, 2.40]     1.49      0.45     [0.42, 0.49]\n   PROX_SHOPPING_MALL 1.48 [1.39, 1.60]     1.22      0.67     [0.63, 0.72]\n        PROX_BUS_STOP 2.85 [2.62, 3.10]     1.69      0.35     [0.32, 0.38]\n          NO_Of_UNITS 1.45 [1.36, 1.56]     1.20      0.69     [0.64, 0.73]\n      FAMILY_FRIENDLY 1.38 [1.30, 1.48]     1.17      0.72     [0.67, 0.77]\n             FREEHOLD 1.44 [1.36, 1.55]     1.20      0.69     [0.65, 0.74]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(check_collinearity(condo.mlr1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Term                VIF          VIF_CI_low     VIF_CI_high   \n Length:14          Min.   :1.146   Min.   :1.093   Min.   :1.229  \n Class :character   1st Qu.:1.389   1st Qu.:1.308   1st Qu.:1.491  \n Mode  :character   Median :1.467   Median :1.377   Median :1.576  \n                    Mean   :1.727   Mean   :1.612   Mean   :1.865  \n                    3rd Qu.:1.826   3rd Qu.:1.701   3rd Qu.:1.973  \n                    Max.   :3.262   Max.   :2.996   Max.   :3.562  \n   SE_factor       Tolerance      Tolerance_CI_low Tolerance_CI_high\n Min.   :1.070   Min.   :0.3066   Min.   :0.2807   Min.   :0.3337   \n 1st Qu.:1.178   1st Qu.:0.5516   1st Qu.:0.5106   1st Qu.:0.5918   \n Median :1.211   Median :0.6820   Median :0.6344   Median :0.7260   \n Mean   :1.297   Mean   :0.6336   Mean   :0.5886   Mean   :0.6744   \n 3rd Qu.:1.350   3rd Qu.:0.7201   3rd Qu.:0.6707   3rd Qu.:0.7647   \n Max.   :1.806   Max.   :0.8729   Max.   :0.8136   Max.   :0.9152   \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr.vif <- check_collinearity(condo.mlr1)\nplot(mlr.vif)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n| VIF value | Interpretation                                   |\n|-----------|--------------------------------------------------|\n| 1         | No correlation between predictors (ideal)        |\n| 1-5       | Moderate correlation; acceptable in most models. |\n| \\>5       | Potential multicollinearity concern              |\n| \\>10      | Serious multicollinearity problems               |\n\nWe can safely conclude that there are no sign of multicollinearity among the independent variables, since all VIF values are less than 10.\n\n#### Test for Non-Linearity\n\nThe code chunk below test linearity assumption by using [`ols_plot_resid_fit()`](https://olsrr.rsquaredacademy.com/reference/ols_plot_resid_fit.html) from **olsrr** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_plot_resid_fit(condo.mlr1)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(condo.mlr1,   #performance pacakge\n            check = \"linearity\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nAccording to the [`check_model()` documentation](https://www.rdocumentation.org/packages/performance/versions/0.12.4/topics/check_model), `check` argument could be one or more of \"all\", \"vif\", \"qq\", \"normality\", \"linearity\", \"ncv\", \"homogeneity\", \"outliers\", \"reqq\", \"pp_check\", \"binned_residuals\" or \"overdispersion\".\"reqq\" is a QQ-plot for random effects and only available for mixed models. \"ncv\" is an alias for \"linearity\", and checks for non-constant variance, i.e. for heteroscedasticity, as well as the linear relationship. By default, all possible checks are performed and plotted.\n:::\n\nSince the majority of data points are scattered around the 0 line, relationships between the dependent variable and independent variables seem linear.\n\n#### Test for Normality Assumption\n\nIf the model’s residuals (the differences between observed and predicted values) are normally distributed, the normality assumption holds. This is crucial for accurate hypothesis testing and confidence intervals.\n\nThe code chunk below uses check_normality() of performance package to perform normality assumption test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_normality(condo.mlr1) # performance package\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Non-normality of residuals detected (p < .001).\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(check_normality(condo.mlr1), type =\"qq\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nQQ plot above below shows that majority of the data points are felt along the zero line.\n\nThe code chunk below uses [`check_model()`](https://easystats.github.io/performance/reference/check_model.html) from performance package to test residuals normality.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(condo.mlr1,\n            check= \"normality\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\nThe figure reveals that the residual of the multiple linear regression model (i.e. condo.mlr1) is resemble normal distribution.\n\nAlternatively, we could do the same tests using **olsrr** package, using following residual diagnostics: ols_plot_resid_box(), ols_plot_resid_hist(), ols_plot_resid_qq() and ols_test_normality() to check normality of residuals. ols_test_correlation()tests independence (autocorrelation).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n ols_test_normality(condo.mlr1) #olsrr package\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-----------------------------------------------\n       Test             Statistic       pvalue  \n-----------------------------------------------\nShapiro-Wilk              0.6856         0.0000 \nKolmogorov-Smirnov        0.1366         0.0000 \nCramer-von Mises         121.0768        0.0000 \nAnderson-Darling         67.9551         0.0000 \n-----------------------------------------------\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_plot_resid_hist(condo.mlr1)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_plot_resid_qq(condo.mlr1) \n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n#### Testing for Spatial Autocorrelation\n\nThe hedonic model uses geographically referenced data, thus it is essential to check for spatial autocorrelation. Traditional OLS regression assumes independent observations, but spatial data often violates this assumption. Spatial autocorrelation occurs when nearby locations exhibit similar (positive) or dissimilar (negative) values, consistent with Tobler’s First Law of Geography. Ignoring it can lead to biased coefficients, incorrect p-values, and model misspecification. Therefore, testing the model’s residuals with Moran’s I is necessary—significant spatial autocorrelation indicates that the model fails to capture important spatial effects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_test_correlation(condo.mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8254074\n```\n\n\n:::\n:::\n\n\nThe OLS autocorrelation value of 0.825 suggests strong positive autocorrelation that the residuals are not independent. This violates the OLS assumption of error independence and should be further tested using Moran’s I for spatial dependence. Significant spatial autocorrelation in the residuals means the model is not capturing the full spatial story, some spatial dependence is left unexplained.\n\nWe first save the residuals as a data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr.output <- as.data.frame(condo.mlr1$residuals)\n```\n:::\n\n\nNext,we join the residuals with condo_resale.sf object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf <- cbind(condo_resale.sf, mlr.output) %>%\n  rename(`MLR_RES`= `condo.mlr1.residuals`)\n```\n:::\n\n\nNext, we plot the distribution of residuals using functions from tmap package on an interactive map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_svy21) +\n  tm_polygons(fill_alpha =0.4) +\n  tm_shape(condo_resale.sf) +\n  tm_dots( fill = \"MLR_RES\",\n           size = 0.7,\n           col = \"black\",\n           fill.scale = tm_scale(\n             n= 10,\n             value = rev(brewer.pal(11, \"RdBu\")),\n             style = \"quantile\",\n             midpoint = NA),\n           fill.legend = tm_legend(title = \"Residuals\")) +\n  \n  tm_title(\"LM Residuals (Quantile Classification)\") +\n  tm_layout(legdend.outside = TRUE) +\n  tm_view(set_zoom_limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\nEach dot represents a condo resale residual (actual - predicted):\n\n-   Green dots (positive): model underpredicted (actual \\> predicted).\n\n-   Purple dots (negative): model overpredicted (actual \\< predicted).\n\nIf residuals were spatially random, green and purple dots would be evenly scattered across Singapore.But it is not the case here. Further, the coexistence of overestimates and underestimates within the same region indicates that the OLS model cannot fully capture local variations in housing market dynamics.\n\nNext we can confirm with Moran’s I test on residuals.\n\nFirst, we compute distance-based weight matrix using [`st_dist_band()`](https://sfdep.josiahparry.com/reference/st_dist_band) function of **sfdep.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf <- condo_resale.sf %>%\n  mutate(nb = st_dist_band(st_geometry(geometry), upper = 1500),\n         wt = st_weights(nb, style = \"W\"),\n         .before = 1)\n```\n:::\n\n\nThen, we use [`global_moran_perm()`](https://sfdep.josiahparry.com/reference/global_moran_perm) of **sfdep** package conduct Moran's I test for residual spatial autocorrelation with Monte Carlo Simulations (500 times).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nglobal_moran_perm(condo_resale.sf$MLR_RES,\n                  nb = condo_resale.sf$nb,\n                  wt = condo_resale.sf$wt,\n                  alternative = \"two.sided\",\n                  nsim = 499)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 500 \n\nstatistic = 0.14389, observed rank = 500, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe Global Moran’s I value of 0.1439 (p \\< 0.05) indicates a statistically significant positive spatial autocorrelation, suggesting a mild clustering pattern across the study area.\n::::\n\n## Building Hedonic Pricing Models Using GWmodel Package\n\nIn this section, we build hedonic pricing models using both the fixed and adaptive bandwidth schemes.\n\n### Computing Fixed Bandwidth\n\nThe `bw.gwr()` function from the **GWModel** package determines the optimal fixed bandwidth (`**adaptive** = FALSE`) and uses a stopping rule based on either the cross-validation (CV) or AICc (AIC) approach, as specified by the **approach** argument. Here, we use the AIC approach while the alternative method CV tends to produce a smaller bandwidth, which is more suitable for capturing local spatial variation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.fixed <- bw.gwr(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE    +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK + \n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL   + \n    PROX_BUS_STOP   + NO_Of_UNITS + FAMILY_FRIENDLY + \n    FREEHOLD, \n  data=condo_resale.sf, \n  approach = \"AIC\",\n  kernel = \"gaussian\",\n  adaptive = FALSE,\n  longlat = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFixed bandwidth: 17660.96 AICc value: 42937.77 \nFixed bandwidth: 10917.26 AICc value: 42886.26 \nFixed bandwidth: 6749.419 AICc value: 42757.54 \nFixed bandwidth: 4173.553 AICc value: 42565.01 \nFixed bandwidth: 2581.58 AICc value: 42368.05 \nFixed bandwidth: 1597.687 AICc value: 42256.42 \nFixed bandwidth: 989.6077 AICc value: 42262.3 \nFixed bandwidth: 1973.501 AICc value: 42279.95 \nFixed bandwidth: 1365.421 AICc value: 42254.72 \nFixed bandwidth: 1221.873 AICc value: 42255.41 \nFixed bandwidth: 1454.139 AICc value: 42254.82 \nFixed bandwidth: 1310.591 AICc value: 42254.84 \nFixed bandwidth: 1399.309 AICc value: 42254.71 \nFixed bandwidth: 1420.252 AICc value: 42254.73 \nFixed bandwidth: 1386.365 AICc value: 42254.7 \nFixed bandwidth: 1378.365 AICc value: 42254.71 \nFixed bandwidth: 1391.309 AICc value: 42254.7 \n```\n\n\n:::\n:::\n\n\nAIC Recommended bandwidth is 1,391.309 metres, since we are using projected crs measured in metres.\nCV Recommended bandwidth is 971.340 metres, since we are using projected crs measured in metres.\n\n### GWModel method - fixed bandwith\n\nThe code chunk below calibrates the GWR model using fixed bandwidth and Gaussian kernel.`gwr.basic()` is a function from the **GWModel** package that performs basic Geographically Weighted Regression (GWR).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.fixed <- gwr.basic(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE    +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK +\n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL   + \n    PROX_BUS_STOP   + NO_Of_UNITS + FAMILY_FRIENDLY + \n    FREEHOLD, \n  data=condo_resale.sf, \n  bw=bw.fixed, \n  kernel = 'gaussian', \n  longlat = FALSE)\n```\n:::\n\n\nThe class of GWR model is \"gwrm\". The report belew shows\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.fixed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-10-18 15:55:35.765807 \n   Call:\n   gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + \n    PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + \n    PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + \n    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, \n    data = condo_resale.sf, bw = bw.fixed, kernel = \"gaussian\", \n    longlat = FALSE)\n\n   Dependent (y) variable:  SELLING_PRICE\n   Independent variables:  AREA_SQM AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE PROX_URA_GROWTH_AREA PROX_MRT PROX_PARK PROX_PRIMARY_SCH PROX_SHOPPING_MALL PROX_BUS_STOP NO_Of_UNITS FAMILY_FRIENDLY FREEHOLD\n   Number of data points: 1436\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n     Min       1Q   Median       3Q      Max \n-3470778  -298119   -23481   248917 12234210 \n\n   Coefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)           527633.22  108183.22   4.877 1.20e-06 ***\n   AREA_SQM               12777.52     367.48  34.771  < 2e-16 ***\n   AGE                   -24687.74    2754.84  -8.962  < 2e-16 ***\n   PROX_CBD              -77131.32    5763.12 -13.384  < 2e-16 ***\n   PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** \n   PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***\n   PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***\n   PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***\n   PROX_PARK             570504.81   65507.03   8.709  < 2e-16 ***\n   PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** \n   PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***\n   PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***\n   NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** \n   FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** \n   FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 756000 on 1421 degrees of freedom\n   Multiple R-squared: 0.6507\n   Adjusted R-squared: 0.6472 \n   F-statistic: 189.1 on 14 and 1421 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 8.120609e+14\n   Sigma(hat): 752522.9\n   AIC:  42966.76\n   AICc:  42967.14\n   BIC:  41731.39\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Fixed bandwidth: 1386.365 \n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                               Min.     1st Qu.      Median     3rd Qu.\n   Intercept            -5.0947e+06  7.5228e+04  9.6933e+05  1.6560e+06\n   AREA_SQM              2.5558e+03  5.4041e+03  7.6995e+03  1.2569e+04\n   AGE                  -8.4563e+04 -2.1045e+04 -1.1083e+04 -5.3192e+03\n   PROX_CBD             -3.0121e+06 -2.2299e+05 -1.0207e+05 -5.3900e+04\n   PROX_CHILDCARE       -3.6679e+06 -1.7018e+05 -1.6108e+04  2.4420e+05\n   PROX_ELDERLYCARE     -4.9526e+05 -4.0047e+04  7.6715e+04  1.9650e+05\n   PROX_URA_GROWTH_AREA -3.0350e+05 -3.0201e+04  5.1598e+04  1.5573e+05\n   PROX_MRT             -2.6892e+06 -3.9441e+05 -2.3485e+05 -1.3171e+05\n   PROX_PARK            -9.1626e+05 -1.2375e+05  4.7999e+04  4.0312e+05\n   PROX_PRIMARY_SCH     -4.7607e+05 -1.2189e+05  2.9963e+04  3.0890e+05\n   PROX_SHOPPING_MALL   -9.7562e+05 -1.2594e+05 -1.2552e+04  1.0019e+05\n   PROX_BUS_STOP        -8.4504e+05  8.8484e+04  3.7699e+05  1.4980e+06\n   NO_Of_UNITS          -1.2111e+03 -3.4940e+02 -5.8441e+01  1.0022e+02\n   FAMILY_FRIENDLY      -1.3608e+06 -5.1541e+04  1.0951e+04  1.5911e+05\n   FREEHOLD             -1.1559e+05  9.5013e+04  2.0430e+05  3.5295e+05\n                             Max.\n   Intercept            4639265.4\n   AREA_SQM               19642.4\n   AGE                    41275.9\n   PROX_CBD              272116.0\n   PROX_CHILDCARE       1776212.0\n   PROX_ELDERLYCARE     2742988.5\n   PROX_URA_GROWTH_AREA 3038754.5\n   PROX_MRT             1349867.9\n   PROX_PARK            1102849.3\n   PROX_PRIMARY_SCH     2148894.9\n   PROX_SHOPPING_MALL    668261.7\n   PROX_BUS_STOP        4267600.2\n   NO_Of_UNITS             2174.3\n   FAMILY_FRIENDLY      1289044.9\n   FREEHOLD             1001304.5\n   ************************Diagnostic information*************************\n   Number of data points: 1436 \n   Effective number of parameters (2trace(S) - trace(S'S)): 302.5667 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 1133.433 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 42254.7 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 41902.94 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 42011.36 \n   Residual sum of squares: 3.334499e+14 \n   R-square value:  0.8565589 \n   Adjusted R-square value:  0.8182339 \n\n   ***********************************************************************\n   Program stops at: 2025-10-18 15:55:36.869823 \n```\n\n\n:::\n:::\n\n\nAIC method:\n\nThe GWR model achieved an AICc value of 42,254.7, which is significantly lower than that of the global multiple linear regression model (42,967.10), which means a better fit and simplicity. The model also produced an R2 of 0.857 and an adjusted R2 of 0.818. The GWR explains over 80% of the spatial variation in condominium resale prices. However the wider bandwidth does not necessarily produce a higher R2. We should always try out both options and find a better performer.\n\nCV method:\n\nThe GWR model achieved an AICc value of 42,263.61, which is significantly lower than that of the global multiple linear regression model (42,967.10), which means a better fit and simplicity. The model also produced an R2 of 0.891 and an adjusted R2 of 0.843. The GWR explains over 80% of the spatial variation in condominium resale prices.\n\n### Building Adaptive Bandwidth GWR Model\n\nNext we calibrate the GWR-based hedonic pricing model by using adaptive bandwidth approach.\n\n#### Computing the Adaptive Bandwidth\n\nThe code chunk below calculates the adaptive bandwidth by setting the **adaptive** argument to **TRUE**, allowing the bandwidth to vary according to the density of data points across the regions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.adaptive <- bw.gwr(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE  + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE    +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK + \n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL   + \n    PROX_BUS_STOP   + NO_Of_UNITS + FAMILY_FRIENDLY + \n    FREEHOLD, \n  data=condo_resale.sf, \n  approach = \"AIC\",\n  kernel = \"gaussian\",\n  adaptive = TRUE,\n  longlat = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdaptive bandwidth (number of nearest neighbours): 895 AICc value: 42879.45 \nAdaptive bandwidth (number of nearest neighbours): 561 AICc value: 42823.52 \nAdaptive bandwidth (number of nearest neighbours): 354 AICc value: 42677.14 \nAdaptive bandwidth (number of nearest neighbours): 226 AICc value: 42484.37 \nAdaptive bandwidth (number of nearest neighbours): 147 AICc value: 42353.27 \nAdaptive bandwidth (number of nearest neighbours): 98 AICc value: 42280.68 \nAdaptive bandwidth (number of nearest neighbours): 68 AICc value: 42201.18 \nAdaptive bandwidth (number of nearest neighbours): 49 AICc value: 42100.66 \nAdaptive bandwidth (number of nearest neighbours): 37 AICc value: 42055.68 \nAdaptive bandwidth (number of nearest neighbours): 30 AICc value: 41982.22 \nAdaptive bandwidth (number of nearest neighbours): 25 AICc value: 42003.33 \nAdaptive bandwidth (number of nearest neighbours): 32 AICc value: 42035.41 \nAdaptive bandwidth (number of nearest neighbours): 27 AICc value: 41978.63 \nAdaptive bandwidth (number of nearest neighbours): 27 AICc value: 41978.63 \n```\n\n\n:::\n:::\n\n\nThe output values are **not in metres** as the bandwidth is the number of nearest neighbours, not a physical distance. AIC method recommends the optimal adaptive bandwidth of 27 means each local regression is calibrated using the **27 nearest neighbouring observations**, while CV recommends the optimal adaptive bandwidth of 30.\n\n### Constructing the Adaptive Bandwidth GWR Model\n\nSimilarly, we build the GWR model using adpative bandwidth and Gaussian Kernel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive <- gwr.basic(\n  formula = SELLING_PRICE ~ AREA_SQM + AGE + \n    PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +\n    PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK +\n    PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_BUS_STOP +\n    NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD,\n  data=condo_resale.sf, \n  bw=bw.adaptive, \n  kernel = 'gaussian', \n  adaptive=TRUE, \n  longlat = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-10-18 15:55:52.022127 \n   Call:\n   gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + \n    PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + \n    PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + \n    PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, \n    data = condo_resale.sf, bw = bw.adaptive, kernel = \"gaussian\", \n    adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  SELLING_PRICE\n   Independent variables:  AREA_SQM AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE PROX_URA_GROWTH_AREA PROX_MRT PROX_PARK PROX_PRIMARY_SCH PROX_SHOPPING_MALL PROX_BUS_STOP NO_Of_UNITS FAMILY_FRIENDLY FREEHOLD\n   Number of data points: 1436\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n     Min       1Q   Median       3Q      Max \n-3470778  -298119   -23481   248917 12234210 \n\n   Coefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)           527633.22  108183.22   4.877 1.20e-06 ***\n   AREA_SQM               12777.52     367.48  34.771  < 2e-16 ***\n   AGE                   -24687.74    2754.84  -8.962  < 2e-16 ***\n   PROX_CBD              -77131.32    5763.12 -13.384  < 2e-16 ***\n   PROX_CHILDCARE       -318472.75  107959.51  -2.950 0.003231 ** \n   PROX_ELDERLYCARE      185575.62   39901.86   4.651 3.61e-06 ***\n   PROX_URA_GROWTH_AREA   39163.25   11754.83   3.332 0.000885 ***\n   PROX_MRT             -294745.11   56916.37  -5.179 2.56e-07 ***\n   PROX_PARK             570504.81   65507.03   8.709  < 2e-16 ***\n   PROX_PRIMARY_SCH      159856.14   60234.60   2.654 0.008046 ** \n   PROX_SHOPPING_MALL   -220947.25   36561.83  -6.043 1.93e-09 ***\n   PROX_BUS_STOP         682482.22  134513.24   5.074 4.42e-07 ***\n   NO_Of_UNITS             -245.48      87.95  -2.791 0.005321 ** \n   FAMILY_FRIENDLY       146307.58   46893.02   3.120 0.001845 ** \n   FREEHOLD              350599.81   48506.48   7.228 7.98e-13 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 756000 on 1421 degrees of freedom\n   Multiple R-squared: 0.6507\n   Adjusted R-squared: 0.6472 \n   F-statistic: 189.1 on 14 and 1421 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 8.120609e+14\n   Sigma(hat): 752522.9\n   AIC:  42966.76\n   AICc:  42967.14\n   BIC:  41731.39\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 27 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                               Min.     1st Qu.      Median     3rd Qu.\n   Intercept            -3.4055e+08 -4.9698e+05  7.6667e+05  1.6291e+06\n   AREA_SQM              3.2900e+03  5.5381e+03  7.6847e+03  1.2674e+04\n   AGE                  -1.0016e+05 -2.7556e+04 -1.3592e+04 -4.6598e+03\n   PROX_CBD             -4.0881e+06 -1.9515e+05 -7.3518e+04  2.9526e+04\n   PROX_CHILDCARE       -1.7059e+06 -2.6967e+05 -1.2514e+04  3.4777e+05\n   PROX_ELDERLYCARE     -2.2412e+06 -9.4985e+04  7.9372e+04  3.2765e+05\n   PROX_URA_GROWTH_AREA -1.8375e+07 -2.3765e+04  5.7504e+04  2.9631e+05\n   PROX_MRT             -4.5351e+07 -6.2318e+05 -2.0888e+05 -3.8964e+04\n   PROX_PARK            -1.0166e+08 -2.0084e+05  1.1152e+05  4.4450e+05\n   PROX_PRIMARY_SCH     -4.6505e+06 -1.9579e+05 -9.1754e+03  4.3824e+05\n   PROX_SHOPPING_MALL   -2.4269e+06 -1.4053e+05 -1.3684e+04  1.5823e+05\n   PROX_BUS_STOP        -2.1436e+06 -8.7705e+04  4.1820e+05  1.2784e+06\n   NO_Of_UNITS          -3.2993e+03 -2.2606e+02 -2.1790e+01  1.4231e+02\n   FAMILY_FRIENDLY      -4.0477e+06 -6.5054e+04  2.2989e+04  1.9452e+05\n   FREEHOLD             -1.0164e+08  2.4578e+04  1.8212e+05  3.8182e+05\n                              Max.\n   Intercept            55107367.9\n   AREA_SQM                23242.4\n   AGE                    265480.4\n   PROX_CBD             26220365.8\n   PROX_CHILDCARE        3565627.3\n   PROX_ELDERLYCARE     93434431.6\n   PROX_URA_GROWTH_AREA 25096284.3\n   PROX_MRT              9223676.9\n   PROX_PARK             2754387.0\n   PROX_PRIMARY_SCH      4618809.5\n   PROX_SHOPPING_MALL   39514834.8\n   PROX_BUS_STOP        13319341.1\n   NO_Of_UNITS              9878.1\n   FAMILY_FRIENDLY       2315112.2\n   FREEHOLD              1876281.2\n   ************************Diagnostic information*************************\n   Number of data points: 1436 \n   Effective number of parameters (2trace(S) - trace(S'S)): 393.0807 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 1042.919 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 41978.63 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 41453.88 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 42070.13 \n   Residual sum of squares: 2.305296e+14 \n   R-square value:  0.9008324 \n   Adjusted R-square value:  0.8634199 \n\n   ***********************************************************************\n   Program stops at: 2025-10-18 15:55:53.421721 \n```\n\n\n:::\n:::\n\n\nThe report for AIC method indicates AICc of adaptive bandwidth GWR model  is reduced from 42,254.7 to 41978.63. Also we see improved R-square 0.901 and Adjusted R-square is 0.863. This time Adaptive AIC method outperform the CV method.\n\nThe report for CV method indicatesAICc of adaptive bandwidth GWR model  is reduced from 42263.61.to 41982.22. Also we see improved R-square 0.891 and Adjusted R-square is 0.856.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(gwr.adaptive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 7\n $ GW.arguments :List of 11\n  ..$ formula  :Class 'formula'  language SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +      PROX_URA_GROWTH_AREA + PROX_| __truncated__ ...\n  .. .. ..- attr(*, \".Environment\")=<environment: R_GlobalEnv> \n  ..$ rp.given : logi FALSE\n  ..$ hatmatrix: logi TRUE\n  ..$ bw       : num 27\n  ..$ kernel   : chr \"gaussian\"\n  ..$ adaptive : logi TRUE\n  ..$ p        : num 2\n  ..$ theta    : num 0\n  ..$ longlat  : logi FALSE\n  ..$ DM.given : logi FALSE\n  ..$ F123.test: logi FALSE\n $ GW.diagnostic:List of 8\n  ..$ RSS.gw  : num 2.31e+14\n  ..$ AIC     : num 41454\n  ..$ AICc    : num 41979\n  ..$ enp     : num 393\n  ..$ edf     : num 1043\n  ..$ gw.R2   : num 0.901\n  ..$ gwR2.adj: num 0.863\n  ..$ BIC     : num 42070\n $ lm           :List of 14\n  ..$ coefficients : Named num [1:15] 527633 12778 -24688 -77131 -318473 ...\n  .. ..- attr(*, \"names\")= chr [1:15] \"(Intercept)\" \"AREA_SQM\" \"AGE\" \"PROX_CBD\" ...\n  ..$ residuals    : Named num [1:1436] -1489100 415495 194130 1088993 -114969 ...\n  .. ..- attr(*, \"names\")= chr [1:1436] \"1\" \"2\" \"3\" \"4\" ...\n  ..$ effects      : Named num [1:1436] -66361417 -32409518 6712129 -16329091 604473 ...\n  .. ..- attr(*, \"names\")= chr [1:1436] \"(Intercept)\" \"AREA_SQM\" \"AGE\" \"PROX_CBD\" ...\n  ..$ rank         : int 15\n  ..$ fitted.values: Named num [1:1436] 4489100 3464505 3130870 3161007 1514969 ...\n  .. ..- attr(*, \"names\")= chr [1:1436] \"1\" \"2\" \"3\" \"4\" ...\n  ..$ assign       : int [1:15] 0 1 2 3 4 5 6 7 8 9 ...\n  ..$ qr           :List of 5\n  .. ..$ qr   : num [1:1436, 1:15] -37.8946 0.0264 0.0264 0.0264 0.0264 ...\n  .. .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. .. ..$ : chr [1:1436] \"1\" \"2\" \"3\" \"4\" ...\n  .. .. .. ..$ : chr [1:15] \"(Intercept)\" \"AREA_SQM\" \"AGE\" \"PROX_CBD\" ...\n  .. .. ..- attr(*, \"assign\")= int [1:15] 0 1 2 3 4 5 6 7 8 9 ...\n  .. ..$ qraux: num [1:15] 1.03 1.07 1.05 1.03 1.01 ...\n  .. ..$ pivot: int [1:15] 1 2 3 4 5 6 7 8 9 10 ...\n  .. ..$ tol  : num 1e-07\n  .. ..$ rank : int 15\n  .. ..- attr(*, \"class\")= chr \"qr\"\n  ..$ df.residual  : int 1421\n  ..$ xlevels      : Named list()\n  ..$ call         : language lm(formula = formula, data = data)\n  ..$ terms        :Classes 'terms', 'formula'  language SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +      PROX_URA_GROWTH_AREA + PROX_| __truncated__ ...\n  .. .. ..- attr(*, \"variables\")= language list(SELLING_PRICE, AREA_SQM, AGE, PROX_CBD, PROX_CHILDCARE, PROX_ELDERLYCARE,      PROX_URA_GROWTH_AREA, PROX_MR| __truncated__ ...\n  .. .. ..- attr(*, \"factors\")= int [1:15, 1:14] 0 1 0 0 0 0 0 0 0 0 ...\n  .. .. .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. .. .. ..$ : chr [1:15] \"SELLING_PRICE\" \"AREA_SQM\" \"AGE\" \"PROX_CBD\" ...\n  .. .. .. .. ..$ : chr [1:14] \"AREA_SQM\" \"AGE\" \"PROX_CBD\" \"PROX_CHILDCARE\" ...\n  .. .. ..- attr(*, \"term.labels\")= chr [1:14] \"AREA_SQM\" \"AGE\" \"PROX_CBD\" \"PROX_CHILDCARE\" ...\n  .. .. ..- attr(*, \"order\")= int [1:14] 1 1 1 1 1 1 1 1 1 1 ...\n  .. .. ..- attr(*, \"intercept\")= int 1\n  .. .. ..- attr(*, \"response\")= int 1\n  .. .. ..- attr(*, \".Environment\")=<environment: R_GlobalEnv> \n  .. .. ..- attr(*, \"predvars\")= language list(SELLING_PRICE, AREA_SQM, AGE, PROX_CBD, PROX_CHILDCARE, PROX_ELDERLYCARE,      PROX_URA_GROWTH_AREA, PROX_MR| __truncated__ ...\n  .. .. ..- attr(*, \"dataClasses\")= Named chr [1:15] \"numeric\" \"numeric\" \"numeric\" \"numeric\" ...\n  .. .. .. ..- attr(*, \"names\")= chr [1:15] \"SELLING_PRICE\" \"AREA_SQM\" \"AGE\" \"PROX_CBD\" ...\n  ..$ model        :'data.frame':\t1436 obs. of  15 variables:\n  .. ..$ SELLING_PRICE       : num [1:1436] 3000000 3880000 3325000 4250000 1400000 ...\n  .. ..$ AREA_SQM            : num [1:1436] 309 290 248 127 145 139 218 141 165 168 ...\n  .. ..$ AGE                 : num [1:1436] 30 32 33 7 28 22 24 24 27 31 ...\n  .. ..$ PROX_CBD            : num [1:1436] 7.94 6.61 6.9 4.04 11.78 ...\n  .. ..$ PROX_CHILDCARE      : num [1:1436] 0.166 0.28 0.429 0.395 0.119 ...\n  .. ..$ PROX_ELDERLYCARE    : num [1:1436] 2.52 1.933 0.502 1.991 1.121 ...\n  .. ..$ PROX_URA_GROWTH_AREA: num [1:1436] 6.62 7.51 6.46 4.91 6.41 ...\n  .. ..$ PROX_MRT            : num [1:1436] 0.561 0.658 0.305 0.691 0.529 ...\n  .. ..$ PROX_PARK           : num [1:1436] 1.171 0.199 0.278 0.983 0.116 ...\n  .. ..$ PROX_PRIMARY_SCH    : num [1:1436] 1.634 0.975 1.472 1.455 0.709 ...\n  .. ..$ PROX_SHOPPING_MALL  : num [1:1436] 2.21 2.937 1.226 0.353 1.308 ...\n  .. ..$ PROX_BUS_STOP       : num [1:1436] 0.103 0.287 0.285 0.299 0.345 ...\n  .. ..$ NO_Of_UNITS         : num [1:1436] 18 20 27 30 30 31 32 32 32 32 ...\n  .. ..$ FAMILY_FRIENDLY     : num [1:1436] 0 0 0 0 0 1 1 0 1 1 ...\n  .. ..$ FREEHOLD            : num [1:1436] 1 1 1 1 1 1 1 1 1 0 ...\n  .. ..- attr(*, \"terms\")=Classes 'terms', 'formula'  language SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +      PROX_URA_GROWTH_AREA + PROX_| __truncated__ ...\n  .. .. .. ..- attr(*, \"variables\")= language list(SELLING_PRICE, AREA_SQM, AGE, PROX_CBD, PROX_CHILDCARE, PROX_ELDERLYCARE,      PROX_URA_GROWTH_AREA, PROX_MR| __truncated__ ...\n  .. .. .. ..- attr(*, \"factors\")= int [1:15, 1:14] 0 1 0 0 0 0 0 0 0 0 ...\n  .. .. .. .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. .. .. .. ..$ : chr [1:15] \"SELLING_PRICE\" \"AREA_SQM\" \"AGE\" \"PROX_CBD\" ...\n  .. .. .. .. .. ..$ : chr [1:14] \"AREA_SQM\" \"AGE\" \"PROX_CBD\" \"PROX_CHILDCARE\" ...\n  .. .. .. ..- attr(*, \"term.labels\")= chr [1:14] \"AREA_SQM\" \"AGE\" \"PROX_CBD\" \"PROX_CHILDCARE\" ...\n  .. .. .. ..- attr(*, \"order\")= int [1:14] 1 1 1 1 1 1 1 1 1 1 ...\n  .. .. .. ..- attr(*, \"intercept\")= int 1\n  .. .. .. ..- attr(*, \"response\")= int 1\n  .. .. .. ..- attr(*, \".Environment\")=<environment: R_GlobalEnv> \n  .. .. .. ..- attr(*, \"predvars\")= language list(SELLING_PRICE, AREA_SQM, AGE, PROX_CBD, PROX_CHILDCARE, PROX_ELDERLYCARE,      PROX_URA_GROWTH_AREA, PROX_MR| __truncated__ ...\n  .. .. .. ..- attr(*, \"dataClasses\")= Named chr [1:15] \"numeric\" \"numeric\" \"numeric\" \"numeric\" ...\n  .. .. .. .. ..- attr(*, \"names\")= chr [1:15] \"SELLING_PRICE\" \"AREA_SQM\" \"AGE\" \"PROX_CBD\" ...\n  ..$ x            : num [1:1436, 1:15] 1 1 1 1 1 1 1 1 1 1 ...\n  .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. ..$ : chr [1:1436] \"1\" \"2\" \"3\" \"4\" ...\n  .. .. ..$ : chr [1:15] \"Intercept\" \"AREA_SQM\" \"AGE\" \"PROX_CBD\" ...\n  .. ..- attr(*, \"assign\")= int [1:15] 0 1 2 3 4 5 6 7 8 9 ...\n  ..$ y            : Named num [1:1436] 3000000 3880000 3325000 4250000 1400000 ...\n  .. ..- attr(*, \"names\")= chr [1:1436] \"1\" \"2\" \"3\" \"4\" ...\n  ..- attr(*, \"class\")= chr \"lm\"\n $ SDF          :Classes 'sf' and 'data.frame':\t1436 obs. of  52 variables:\n  ..$ Intercept              : num [1:1436] 2044700 1773153 3520072 1539855 2341689 ...\n  ..$ AREA_SQM               : num [1:1436] 9560 15390 13016 21340 6783 ...\n  ..$ AGE                    : num [1:1436] -9500 -48975 -25897 -97109 -18166 ...\n  ..$ PROX_CBD               : num [1:1436] -120265 -173035 -266085 4535465 -343211 ...\n  ..$ PROX_CHILDCARE         : num [1:1436] 318045 348815 -194366 286267 55378 ...\n  ..$ PROX_ELDERLYCARE       : num [1:1436] -394644 238275 558022 402764 -144439 ...\n  ..$ PROX_URA_GROWTH_AREA   : num [1:1436] -159576 -31187 -253591 -4781656 340619 ...\n  ..$ PROX_MRT               : num [1:1436] -299593 -2557296 -942767 -2495886 -10315 ...\n  ..$ PROX_PARK              : num [1:1436] -172381 442318 246973 -937538 58302 ...\n  ..$ PROX_PRIMARY_SCH       : num [1:1436] 242732 919399 558785 3340639 49934 ...\n  ..$ PROX_SHOPPING_MALL     : num [1:1436] 302051 -215149 -142023 134574 -21275 ...\n  ..$ PROX_BUS_STOP          : num [1:1436] 1209536 1919406 1450142 8743552 713294 ...\n  ..$ NO_Of_UNITS            : num [1:1436] 106.4 -211.1 19.3 -150.6 15.8 ...\n  ..$ FAMILY_FRIENDLY        : num [1:1436] -9098 152643 -29285 1723148 65079 ...\n  ..$ FREEHOLD               : num [1:1436] 303928 400569 162972 1318502 328412 ...\n  ..$ y                      : num [1:1436] 3000000 3880000 3325000 4250000 1400000 ...\n  ..$ yhat                   : num [1:1436] 2885980 3464956 3621403 5528248 1384433 ...\n  ..$ residual               : num [1:1436] 114020 415044 -296403 -1278248 15567 ...\n  ..$ CV_Score               : num [1:1436] 0 0 0 0 0 0 0 0 0 0 ...\n  ..$ Stud_residual          : num [1:1436] 0.3981 1.1299 -0.8947 -3.2373 0.0465 ...\n  ..$ Intercept_SE           : num [1:1436] 505352 959583 1088657 644452 2188232 ...\n  ..$ AREA_SQM_SE            : num [1:1436] 804 1041 1005 647 1408 ...\n  ..$ AGE_SE                 : num [1:1436] 5755 7873 6772 6339 8401 ...\n  ..$ PROX_CBD_SE            : num [1:1436] 36645 46893 64225 723130 428708 ...\n  ..$ PROX_CHILDCARE_SE      : num [1:1436] 311604 383548 356362 318029 726054 ...\n  ..$ PROX_ELDERLYCARE_SE    : num [1:1436] 117822 121330 145658 153819 360699 ...\n  ..$ PROX_URA_GROWTH_AREA_SE: num [1:1436] 54992 138590 104510 714454 501307 ...\n  ..$ PROX_MRT_SE            : num [1:1436] 181050 426728 290346 310229 399736 ...\n  ..$ PROX_PARK_SE           : num [1:1436] 200556 337273 328846 250084 406910 ...\n  ..$ PROX_PRIMARY_SCH_SE    : num [1:1436] 149035 213215 206844 276594 253671 ...\n  ..$ PROX_SHOPPING_MALL_SE  : num [1:1436] 106789 168563 124684 237238 330589 ...\n  ..$ PROX_BUS_STOP_SE       : num [1:1436] 587417 527904 468907 625950 748597 ...\n  ..$ NO_Of_UNITS_SE         : num [1:1436] 213 233 212 452 316 ...\n  ..$ FAMILY_FRIENDLY_SE     : num [1:1436] 128382 139757 152250 115274 165349 ...\n  ..$ FREEHOLD_SE            : num [1:1436] 113235 170427 146100 149874 215887 ...\n  ..$ Intercept_TV           : num [1:1436] 4.05 1.85 3.23 2.39 1.07 ...\n  ..$ AREA_SQM_TV            : num [1:1436] 11.89 14.78 12.95 32.98 4.82 ...\n  ..$ AGE_TV                 : num [1:1436] -1.65 -6.22 -3.82 -15.32 -2.16 ...\n  ..$ PROX_CBD_TV            : num [1:1436] -3.282 -3.69 -4.143 6.272 -0.801 ...\n  ..$ PROX_CHILDCARE_TV      : num [1:1436] 1.0207 0.9094 -0.5454 0.9001 0.0763 ...\n  ..$ PROX_ELDERLYCARE_TV    : num [1:1436] -3.35 1.96 3.83 2.62 -0.4 ...\n  ..$ PROX_URA_GROWTH_AREA_TV: num [1:1436] -2.902 -0.225 -2.426 -6.693 0.679 ...\n  ..$ PROX_MRT_TV            : num [1:1436] -1.6548 -5.9928 -3.247 -8.0453 -0.0258 ...\n  ..$ PROX_PARK_TV           : num [1:1436] -0.86 1.311 0.751 -3.749 0.143 ...\n  ..$ PROX_PRIMARY_SCH_TV    : num [1:1436] 1.629 4.312 2.701 12.078 0.197 ...\n  ..$ PROX_SHOPPING_MALL_TV  : num [1:1436] 2.8285 -1.2764 -1.1391 0.5673 -0.0644 ...\n  ..$ PROX_BUS_STOP_TV       : num [1:1436] 2.059 3.636 3.093 13.968 0.953 ...\n  ..$ NO_Of_UNITS_TV         : num [1:1436] 0.4988 -0.9061 0.0912 -0.3331 0.0502 ...\n  ..$ FAMILY_FRIENDLY_TV     : num [1:1436] -0.0709 1.0922 -0.1923 14.9483 0.3936 ...\n  ..$ FREEHOLD_TV            : num [1:1436] 2.68 2.35 1.12 8.8 1.52 ...\n  ..$ Local_R2               : num [1:1436] 0.917 0.915 0.913 0.919 0.952 ...\n  ..$ geometry               :sfc_POINT of length 1436; first list element:  'XY' num [1:2] 22085 29952\n  ..- attr(*, \"sf_column\")= chr \"geometry\"\n  ..- attr(*, \"agr\")= Factor w/ 3 levels \"constant\",\"aggregate\",..: NA NA NA NA NA NA NA NA NA NA ...\n  .. ..- attr(*, \"names\")= chr [1:51] \"Intercept\" \"AREA_SQM\" \"AGE\" \"PROX_CBD\" ...\n $ timings      :List of 5\n  ..$ start      : POSIXct[1:1], format: \"2025-10-18 15:55:52\"\n  ..$ calibration: POSIXct[1:1], format: \"2025-10-18 15:55:52\"\n  ..$ diagnostic : POSIXct[1:1], format: \"2025-10-18 15:55:53\"\n  ..$ encapsulate: POSIXct[1:1], format: \"2025-10-18 15:55:53\"\n  ..$ stop       : POSIXct[1:1], format: \"2025-10-18 15:55:53\"\n $ this.call    : language gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + PROX_CHILDCARE +      PROX_ELDERLYCARE + PROX_URA| __truncated__ ...\n $ Ftests       : list()\n - attr(*, \"class\")= chr \"gwrm\"\n```\n\n\n:::\n:::\n\n\n### Visualising GWR Output\n\nThe GWR output includes diagnostic and model evaluation fields stored in the **sf** DataFrame under the **SDF** output list. These contain the observed and predicted y values, residuals, condition numbers, local R2, explanatory variable coefficients, standard errors, and corresponding t-values.\n\n-   Condition Number:\n\nAssesses local multicollinearity. Values above 30 indicate unstable or unreliable local estimates.\n\n-   Local R2: Indicates how well the local model fits observed data (0–1 range). Mapping these values highlights areas where the model performs well or poorly, revealing potential missing variables or spatial non-stationarity.\n\n-   Predicted Values: The fitted y values estimated by the GWR.\n\n-   Residuals: Differences between observed and predicted y; standardised residuals (mean = 0, SD = 1) can be mapped with a cold–hot colour scheme to visualise model performance.\n\n-   Coefficient Standard Errors: Measure the reliability of coefficient estimates. Small standard errors relative to coefficient magnitudes indicate stable estimates, while large errors suggest local collinearity issues.\n\nBy jointly examining the Local R2 and residuals maps, we can identify areas where the model performs well (high Local R2, small residuals) and areas where it performs poorly (low Local R2, large residuals).\n\n### Converting SDF into sf data.frame\n\nThe code chunk below extracts the **SDF** field and convert it to **sf** data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf.adaptive <- st_as_sf(gwr.adaptive$SDF) %>%\n  st_transform(3414)\n```\n:::\n\n\nThen we have a quick look on its columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(condo_resale.sf.adaptive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,436\nColumns: 52\n$ Intercept               <dbl> 2044700.26, 1773153.15, 3520072.36, 1539855.35…\n$ AREA_SQM                <dbl> 9559.598, 15390.155, 13016.013, 21340.305, 678…\n$ AGE                     <dbl> -9500.111, -48975.055, -25897.022, -97109.448,…\n$ PROX_CBD                <dbl> -120265.31, -173034.60, -266084.74, 4535464.61…\n$ PROX_CHILDCARE          <dbl> 318045.039, 348815.035, -194366.004, 286266.93…\n$ PROX_ELDERLYCARE        <dbl> -394643.95, 238275.45, 558021.92, 402763.72, -…\n$ PROX_URA_GROWTH_AREA    <dbl> -159575.59, -31187.00, -253591.14, -4781655.68…\n$ PROX_MRT                <dbl> -299592.54, -2557296.15, -942766.83, -2495885.…\n$ PROX_PARK               <dbl> -172380.89, 442318.02, 246972.65, -937538.48, …\n$ PROX_PRIMARY_SCH        <dbl> 242732.037, 919399.390, 558785.123, 3340638.60…\n$ PROX_SHOPPING_MALL      <dbl> 302051.162, -215149.309, -142022.712, 134573.9…\n$ PROX_BUS_STOP           <dbl> 1209536.14, 1919405.53, 1450141.54, 8743551.68…\n$ NO_Of_UNITS             <dbl> 106.372669, -211.071177, 19.339246, -150.59531…\n$ FAMILY_FRIENDLY         <dbl> -9098.124, 152642.975, -29284.824, 1723147.674…\n$ FREEHOLD                <dbl> 303927.63, 400568.89, 162972.29, 1318502.10, 3…\n$ y                       <dbl> 3000000, 3880000, 3325000, 4250000, 1400000, 1…\n$ yhat                    <dbl> 2885980.3, 3464956.3, 3621402.8, 5528248.5, 13…\n$ residual                <dbl> 114019.686, 415043.736, -296402.814, -1278248.…\n$ CV_Score                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ Stud_residual           <dbl> 0.39812858, 1.12993822, -0.89467945, -3.237264…\n$ Intercept_SE            <dbl> 505352.2, 959583.4, 1088656.5, 644451.8, 21882…\n$ AREA_SQM_SE             <dbl> 803.9810, 1041.2806, 1005.1322, 647.0447, 1408…\n$ AGE_SE                  <dbl> 5754.545, 7873.214, 6772.090, 6339.353, 8401.1…\n$ PROX_CBD_SE             <dbl> 36644.67, 46892.76, 64224.98, 723130.45, 42870…\n$ PROX_CHILDCARE_SE       <dbl> 311604.5, 383548.3, 356362.3, 318029.0, 726053…\n$ PROX_ELDERLYCARE_SE     <dbl> 117822.10, 121329.51, 145658.37, 153818.83, 36…\n$ PROX_URA_GROWTH_AREA_SE <dbl> 54991.59, 138590.35, 104509.67, 714454.45, 501…\n$ PROX_MRT_SE             <dbl> 181049.7, 426727.9, 290345.8, 310229.2, 399736…\n$ PROX_PARK_SE            <dbl> 200556.4, 337273.4, 328846.1, 250084.3, 406910…\n$ PROX_PRIMARY_SCH_SE     <dbl> 149035.4, 213215.4, 206844.1, 276593.8, 253671…\n$ PROX_SHOPPING_MALL_SE   <dbl> 106789.05, 168563.26, 124684.33, 237237.76, 33…\n$ PROX_BUS_STOP_SE        <dbl> 587417.1, 527904.1, 468907.1, 625949.7, 748596…\n$ NO_Of_UNITS_SE          <dbl> 213.2704, 232.9495, 211.9892, 452.1575, 315.82…\n$ FAMILY_FRIENDLY_SE      <dbl> 128381.97, 139756.71, 152249.80, 115274.06, 16…\n$ FREEHOLD_SE             <dbl> 113234.6, 170426.6, 146100.1, 149874.1, 215886…\n$ Intercept_TV            <dbl> 4.04608981, 1.84783643, 3.23340951, 2.38940359…\n$ AREA_SQM_TV             <dbl> 11.890328, 14.780026, 12.949553, 32.981191, 4.…\n$ AGE_TV                  <dbl> -1.6508882, -6.2204656, -3.8240810, -15.318510…\n$ PROX_CBD_TV             <dbl> -3.28193222, -3.69000648, -4.14301022, 6.27198…\n$ PROX_CHILDCARE_TV       <dbl> 1.020669014, 0.909442298, -0.545416851, 0.9001…\n$ PROX_ELDERLYCARE_TV     <dbl> -3.34948996, 1.96387060, 3.83103226, 2.6184291…\n$ PROX_URA_GROWTH_AREA_TV <dbl> -2.90181817, -0.22503007, -2.42648497, -6.6927…\n$ PROX_MRT_TV             <dbl> -1.65475280, -5.99280279, -3.24704810, -8.0452…\n$ PROX_PARK_TV            <dbl> -0.8595132, 1.3114524, 0.7510281, -3.7488897, …\n$ PROX_PRIMARY_SCH_TV     <dbl> 1.62868734, 4.31206879, 2.70147945, 12.0777779…\n$ PROX_SHOPPING_MALL_TV   <dbl> 2.82848439, -1.27637129, -1.13905821, 0.567253…\n$ PROX_BUS_STOP_TV        <dbl> 2.0590756, 3.6358978, 3.0925989, 13.9684567, 0…\n$ NO_Of_UNITS_TV          <dbl> 0.49876913, -0.90608143, 0.09122749, -0.333059…\n$ FAMILY_FRIENDLY_TV      <dbl> -0.07086762, 1.09220500, -0.19234721, 14.94826…\n$ FREEHOLD_TV             <dbl> 2.68405282, 2.35038940, 1.11548393, 8.79739845…\n$ Local_R2                <dbl> 0.9172836, 0.9154542, 0.9132622, 0.9192190, 0.…\n$ geometry                <POINT [m]> POINT (22085.12 29951.54), POINT (25656.…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(gwr.adaptive$SDF$yhat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n  392814  1098774  1383270  1751256  1985895 13892256 \n```\n\n\n:::\n:::\n\n\n### Visualising Local R2\n\nThe code chunks below is used to create an interactive point symbol map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(mpsz_svy21)+\n  tm_polygons(fill_alpha = 0.1) +\ntm_shape(condo_resale.sf.adaptive) +  \n  tm_dots(col = \"Local_R2\",\n          border.col = \"gray60\",\n          border.lwd = 1) +\n  tm_view(set.zoom.limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n### Visualsing R2 in East Region\n\nThe code chunk below creates an interactive choropelth map for distribution of local R2 value in East Region. The east region includes plan areas like Bedok ,Paya Lebar, Tampine and Pasir Ris.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(mpsz[mpsz$REGION_N==\"EAST REGION\", ])+\n  tm_polygons()+\ntm_shape(condo_resale.sf.adaptive) + \n  tm_bubbles(col = \"Local_R2\",palette= \"-RdBu\",\n           size = 0.4,\n           border.col = \"gray60\",\n           border.lwd = 1) +\n  tm_view(set.zoom.limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-64-1.png){width=672}\n:::\n:::\n\n\nThe local R2 means the model explains e.g. 90% of variance in condo selling prices, when R2 value is 0.9.\n\nThe values of local R2 of East Region vary from 80% to over 95%. The west side of East Region demonstrates lower R2 around 90%, compared to 95% east side of the East Region. Bedok has a mix of 80% and 90%.\n\nOverall the Adaptive geographically weighted model (AIC bandwidth method) performs quite well. \n\n\n\n### Visualising Coefficient Estimates\n\nThe code chunks below is used to create an interactive point symbol map for **AREA_SQM**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\nAREA_SQM_SE <- tm_shape(mpsz_svy21)+\n  tm_polygons(alpha = 0.1) +\ntm_shape(condo_resale.sf.adaptive) +  \n  tm_dots(col = \"AREA_SQM_SE\",      #standard error of local coefficient, reliability of local estimate\n          border.col = \"gray60\",\n          border.lwd = 1) +\n  tm_view(set.zoom.limits = c(11,14))\n\nAREA_SQM_TV <- tm_shape(mpsz_svy21)+\n  tm_polygons(alpha = 0.1) +\ntm_shape(condo_resale.sf.adaptive) +  \n  tm_dots(col = \"AREA_SQM_TV\",   # local t-value, statistical significance of local effect\n          border.col = \"gray60\",\n          border.lwd = 1) +\n  tm_view(set.zoom.limits = c(11,14))\n\ntmap_arrange(AREA_SQM_SE, AREA_SQM_TV, \n             asp=1, ncol=2,\n             sync = TRUE)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-65-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\nThe spatial distribution of **AREA_SQM** coefficients indicates that floor area is a reliable and significant predictor of condominium prices in the central and south-eastern regions, where standard errors are lower and t-values are moderate to high. In contrast, the northern and western regions exhibit higher standard errors and lower t-values. The floor area has a less stable and weaker influence on price variation in these areas.\n\nThe code chunks below is used to create an interactive point symbol map for **MRT**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPROX_MRT_SE <- tm_shape(mpsz_svy21)+\n  tm_polygons(alpha = 0.1) +\ntm_shape(condo_resale.sf.adaptive) +  \n  tm_dots(col = \"PROX_MRT_SE\",      #standard error of local coefficient, reliability of local estimate\n          border.col = \"gray60\",\n          border.lwd = 1) +\n  tm_view(set.zoom.limits = c(11,14))\n\nPROX_MRT_TV <- tm_shape(mpsz_svy21)+\n  tm_polygons(alpha = 0.1) +\ntm_shape(condo_resale.sf.adaptive) +  \n  tm_dots(col = \"PROX_MRT_TV\",   # local t-value, statistical significance of local effect\n          border.col = \"gray60\",\n          border.lwd = 1) +\n  tm_view(set.zoom.limits = c(11,14))\n\ntmap_arrange(PROX_MRT_SE, PROX_MRT_TV, \n             asp=1, ncol=2,\n             sync = TRUE)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex07_files/figure-html/unnamed-chunk-66-1.png){width=672}\n:::\n:::\n\n\nThe **PROX_MRT** variable exhibits low standard errors overall, that means stable coefficient estimates across the study area. It shows a strong and statistically significant negative relationship with condominium resale prices in the central and southern subzones. That properties closer to MRT stations tend to have higher prices.\n\nHowever, a few light-coloured subzones, such as Bukit Batok, Bukit Panjang, Bukit Timah, and several areas along the East Coast exhibit non-significant relationships.\n\n\\|t\\| \\< 1.96 means statistically insignificant.\n\n## Reference\n\nGollini I, Lu B, Charlton M, Brunsdon C, Harris P (2015) “GWmodel: an R Package for exploring Spatial Heterogeneity using Geographically Weighted Models”. Journal of Statistical Software, 63(17):1-50, http://www.jstatsoft.org/v63/i17/\n\nLu B, Harris P, Charlton M, Brunsdon C (2014) “The GWmodel R Package: further topics for exploring Spatial Heterogeneity using GeographicallyWeighted Models”. Geo-spatial Information Science 17(2): 85-101, http://www.tandfonline.com/doi/abs/10.1080/1009502.2014.917453\n\nKam, T. S. 13 Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method. R for Geospatial Data Science and Analytics. https://r4gdsa.netlify.app/chap13\n",
    "supporting": [
      "In-class_Ex07_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}