{
  "hash": "1f5b29e1ead49963c30008408472ce9a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"08:Geographically Weighted Predictive Models\"\nauthor: \"Yiqiong PAN\"\ndate: \"22 Oct, 2025\"\ndate-modified: last-modified\n\nexecute:\n  echo: true    # display the code\n  eval: true    # run the code\n  message: false\n  warning: false\n  freeze: true  # do not re-render if nothing edited\n\nformat: \n  html:\n    toc: true\n    code-link: true\n\nnumber-sections: true\nnumber-depth: 5\n\neditor: visual\n---\n\n## Overview\n\nPredictive modelling uses statistical or machine learning techniques to forecast future events based on known data (predictors and outcomes). In **geospatial predictive modelling**, the goal is to understand and predict **how** events occur by incorporating their spatial patterns into the modelling process.\n\nEvents should be **not randomly or uniformly distributed** across space. They are influenced by geospatial factors such as infrastructure, social conditions, and topography (natural landscapes).\n\nBy correlating historical event locations with environmental variables, geospatial predictive models capture these spatial constraints and influences.\n\n### Learning Outcomes\n\nBy completing this hands-on exercise, we learn to:\n\n1.  Prepare training and test datasets using appropriate sampling techniques.\n2.  Calibrate predictive models using both geospatial statistical learning and machine learning methods.\n3.  Compare and select the best-performing model.\n4.  Predict future outcomes using the optimised model.\n\n## The Data\n\nThe study integrates both **aspatial** and **geospatial** datasets to model HDB resale prices in Singapore.\n\n| Dataset | Description | Format |\n|-------------|---------------------------------------------|-------------|\n| Aspatial dataset | HDB Resale data: a list of HDB resale transacted prices in Singapore from Jan 2017 onwards, downloaded from [Data.gov.sg.](Data.gov.sg) | CSV |\n| Geospatial dataset | *P14_SUBZONE_WEB_PL*: a polygon feature data providing information of URA 2014 Master Plan Planning Subzone boundary data, also downloaded from [Data.gov.sg.](Data.gov.sg) | ESRI shapefile |\n| Locational factors with geographic coordinates | Eldercare centres, Hawker centres ,Parks ,Supermarkets ,CHAS clinics ,Childcare services ,Kindergartens downloaded from [Data.gov.sg](Data.gov.sg)  MRT/LRT stations ,Bus stops downloaded from [Datamall.lta.gov.sg](Datamall.lta.gov.sg), | GeoJSON or Shapefile |\n| Locational factors without geographic coordinates | Primary schools, extracted from Data.gov.sg’s school information dataset. CBD coordinates, retrieved from Google. Shopping malls , scraped from [Wikipedia](https://en.wikipedia.org/wiki/List_of_shopping_malls_in_Singapore). Good primary schools , ranked list of popular schools from[Local Salary Forum.](https://www.salary.sg/2021/best-primary-schools-2021-by-popularity/) | CSV |\n\n{tbl-colwidths=\"\\[30,60,10\\]\"}\n\n## Installing and Loading R packages\n\nThere are 8 packages used in this exercise.\n\n|   | Description |\n|------------------------------------|------------------------------------|\n| [GWmodel](https://cran.r-project.org/web/packages/GWmodel/index.html) | Calibrates geographical weighted family of models |\n| [rsample](https://rsample.tidymodels.org/) | Provides functions to create different types of resamples and corresponding classes for their analysis. |\n| [sf](https://r-spatial.github.io/sf/) | Handles importing, managing, and processing vector-based geospatial data |\n| [tidyverse](https://www.tidyverse.org/) | A collection of R packages for data wrangling and visualisation, including **readr**, **dplyr**, and **ggplot2**. |\n| [tmap](https://r-tmap.github.io/tmap/) | Creates cartographic quality static and interactive thematic (choropleth) maps. |\n| [SpatialML](https://cran.r-project.org/web/packages/SpatialML/index.html) | Allows for a geographically weighted random forest regression including a function to find the optical bandwidth.  |\n| [Metrics](https://cran.r-project.org/web/packages/Metrics/index.html) | Implements metrics for regression, time series, binary classification, classification, and information retrieval problems. |\n| [spdep](https://cran.r-project.org/web/packages/spdep/index.html) | Provides tools for spatial dependence: building neighbour lists, spatial weights, and spatial autocorrelation analysis. |\n\n{tbl-colwidths=\"\\[15,85\\]\"}\n\nWe load the following packages into R environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, GWmodel, SpatialML, \n               tmap, rsample, Metrics, tidyverse)\n```\n:::\n\n\n\n## Preparing Data\n\n\n### Reading data file to rds\n\nWe first read the input data sets that is saved in `simple feature` data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmdata <- read_rds(\"data/rawdata/mdata.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(mdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"resale_price\"             \"floor_area_sqm\"          \n [3] \"storey_order\"             \"remaining_lease_mths\"    \n [5] \"PROX_CBD\"                 \"PROX_ELDERLYCARE\"        \n [7] \"PROX_HAWKER\"              \"PROX_MRT\"                \n [9] \"PROX_PARK\"                \"PROX_GOOD_PRISCH\"        \n[11] \"PROX_MALL\"                \"PROX_CHAS\"               \n[13] \"PROX_SUPERMARKET\"         \"WITHIN_350M_KINDERGARTEN\"\n[15] \"WITHIN_350M_CHILDCARE\"    \"WITHIN_350M_BUS\"         \n[17] \"WITHIN_1KM_PRISCH\"        \"geometry\"                \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mdata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 15,901\nColumns: 18\n$ resale_price             <dbl> 330000, 360000, 370000, 375000, 380000, 38000…\n$ floor_area_sqm           <dbl> 92, 91, 92, 99, 92, 92, 92, 92, 93, 91, 91, 9…\n$ storey_order             <int> 1, 3, 1, 2, 2, 4, 3, 2, 4, 3, 3, 3, 4, 3, 2, …\n$ remaining_lease_mths     <dbl> 684, 738, 733, 700, 715, 732, 706, 745, 731, …\n$ PROX_CBD                 <dbl> 8.824749, 9.841309, 9.560780, 9.609731, 8.351…\n$ PROX_ELDERLYCARE         <dbl> 0.2514065, 0.6318448, 1.0824168, 0.3473195, 0…\n$ PROX_HAWKER              <dbl> 0.44182653, 0.26972560, 0.25829513, 0.4364751…\n$ PROX_MRT                 <dbl> 0.6885144, 1.0969096, 0.8862859, 1.4093169, 0…\n$ PROX_PARK                <dbl> 0.7450859, 0.4294870, 0.7800777, 0.1776163, 0…\n$ PROX_GOOD_PRISCH         <dbl> 1.2703931, 0.4045792, 2.0942375, 0.1375070, 1…\n$ PROX_MALL                <dbl> 0.5534331, 1.0677012, 0.9751113, 1.1752392, 1…\n$ PROX_CHAS                <dbl> 1.364596e-01, 2.569863e-01, 1.906189e-01, 2.9…\n$ PROX_SUPERMARKET         <dbl> 0.2708222, 0.3101889, 0.3187560, 0.4586748, 0…\n$ WITHIN_350M_KINDERGARTEN <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, …\n$ WITHIN_350M_CHILDCARE    <int> 6, 5, 2, 3, 3, 2, 3, 4, 3, 2, 4, 4, 4, 5, 2, …\n$ WITHIN_350M_BUS          <int> 8, 8, 8, 7, 6, 9, 6, 6, 5, 4, 10, 5, 6, 9, 8,…\n$ WITHIN_1KM_PRISCH        <int> 2, 2, 1, 2, 2, 1, 3, 2, 2, 2, 2, 2, 3, 2, 2, …\n$ geometry                 <POINT [m]> POINT (29179.92 38822.08), POINT (28423…\n```\n\n\n:::\n:::\n\n\n\n### Data Sampling\n\nWe split the entire data into 65% training and 35% test by using `initial_split()` of **rsample** package, which belongs to **tigymodels** ecosystem. Then we extract the training set and test set from a data split object created by functions `initial_split()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nresale_split <- initial_split(mdata, prop = 6.5/10,)\ntrain_data <- training(resale_split)\ntest_data <- testing(resale_split)\n```\n:::\n\n\nWe save both files on the disk. \n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(train_data, \"data/model/train_data.rds\")\nwrite_rds(test_data, \"data/model/test_data.rds\")\n```\n:::\n\n\n### Computing Correlation Matrix\n\nBefore loading predictor into a predictive model, let's plot the correlation matrix to check if there is any sign of multicolinearity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmdata_nogeo <- st_drop_geometry(mdata)\ncorrplot::corrplot(cor(mdata_nogeo[, 2:17]),\n                   diag = FALSE, # hide diagonal or TRUE\n                   order = \"AOE\",# angular order of the eigenvectors\" /original/AOE/FPC/hclust/alphabet\n                   tl.pos = \"td\", # text label position: top and diagonal/lt/n null\n                   tl.cex = 0.5,  # text label size: shrinks 50%\n                   method = \"number\",  # display number/circle/color/shade/pie\n                   type = \"upper\") #show only the upper triangle/full/lower\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-7-1.png){width=1344}\n:::\n:::\n\n\nThere is no sign of multicolinearity since all correlation values are below **0.8**.\n\n## Retriving the Stored Data\n\nWe load the saved data into R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data <- read_rds(\"data/model/train_data.rds\")\ntest_data <- read_rds(\"data/model/test_data.rds\")\n```\n:::\n\n\n\n\n## Building a Non-spatial Multiple Linear Regression\n\nA multiple regression model is built as a base line model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprice_mlr <- lm(resale_price ~ floor_area_sqm +                   # target ~ independent variables\n                  storey_order + remaining_lease_mths +\n                  PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +\n                  PROX_MRT + PROX_PARK + PROX_MALL + \n                  PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +\n                  WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +\n                  WITHIN_1KM_PRISCH,\n                data=train_data)\nsummary(price_mlr)\n```\n:::\n\nThe regression summary report indicates that the model slightly underestimates HDB resale prices, as shown by the residual median of –1,930. However, the R2 value of 0.7373 suggests that the model explains approximately 74% of the variation in HDB resale prices since 2017, which exhibits good predictive performance overall.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(price_mlr, \"data/model/price_mlr.rds\" ) \n```\n:::\n\n\n## gwr Predictive Method\n\nNext we build and calibrate geographically weighted regression model to preidict HDB resales prices using methods from [GWmodel](https://cran.r-project.org/web/packages/GWmodel/index.html) package.\n\nSomehow error occurred in the later step `Computing Predicted Values of the Test Data` suggests that we need to convert the data to spatial objects first. \nConvert the training and test data into `SpatialPointDateFrame` for use in GWR:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data_sp <- as(train_data, \"Spatial\")\ntest_data_sp <- as(test_data, \"Spatial\")\ntrain_data_sp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatialPointsDataFrame \nfeatures    : 10335 \nextent      : 11597.31, 42623.63, 28217.39, 48741.06  (xmin, xmax, ymin, ymax)\ncrs         : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs \nvariables   : 17\nnames       : resale_price, floor_area_sqm, storey_order, remaining_lease_mths,          PROX_CBD,     PROX_ELDERLYCARE,        PROX_HAWKER,           PROX_MRT,          PROX_PARK,   PROX_GOOD_PRISCH,        PROX_MALL,            PROX_CHAS,     PROX_SUPERMARKET, WITHIN_350M_KINDERGARTEN, WITHIN_350M_CHILDCARE, ... \nmin values  :       218000,             74,            1,                  555, 0.999393538715878, 1.98943787433087e-08, 0.0333358643817954, 0.0220407324774434, 0.0441643212802781, 0.0652540365486641,                0, 6.20621206270077e-09, 1.21715176356525e-07,                        0,                     0, ... \nmax values  :      1186888,            133,           17,                 1164,  19.6500691667807,     3.30163731686804,   2.86763031236184,   2.13060636038504,   2.41313695915468,   10.6223726149914, 2.27100643784442,    0.808332738794272,     1.57131703651196,                        7,                    20, ... \n```\n\n\n:::\n\n```{.r .cell-code}\ntest_data_sp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass       : SpatialPointsDataFrame \nfeatures    : 5566 \nextent      : 11597.31, 42623.63, 28287.8, 48669.59  (xmin, xmax, ymin, ymax)\ncrs         : +proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1 +x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs \nvariables   : 17\nnames       : resale_price, floor_area_sqm, storey_order, remaining_lease_mths,         PROX_CBD,     PROX_ELDERLYCARE,        PROX_HAWKER,           PROX_MRT,          PROX_PARK,   PROX_GOOD_PRISCH,        PROX_MALL,            PROX_CHAS,     PROX_SUPERMARKET, WITHIN_350M_KINDERGARTEN, WITHIN_350M_CHILDCARE, ... \nmin values  :       230888,             74,            1,                  546, 1.00583660772922, 3.34897933104965e-07, 0.0474019664161957, 0.0414043955932523, 0.0502664084494264, 0.0907500295577619,                0, 4.55547870890763e-09, 1.21715176356525e-07,                        0,                     0, ... \nmax values  :      1050000,            138,           14,                 1151,  19.632402730488,     3.30163731686804,   2.83106651960209,   2.13060636038504,   2.41313695915468,   10.6169590126272, 2.26056404492346,     0.79249074802552,     1.53786629004208,                        7,                    16, ... \n```\n\n\n:::\n:::\n\n\n\n\n\n###  Computing Adaptive Bandwidth\n\n\n\nWe use the `bw.gwr()` function from the **GWmodel** package to determine the optimal bandwidth. The “CV” (Cross Validation) method is chosen for calibration because, between the two available options “CV” and “AIC”, the CV method generally produces a smaller bandwidth, allowing the model to capture more local variation in the data.\n\n\n\nThe code chunk below computes and saves the optimal bandwidth. The search can be time consuming and computationally intensive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_adaptive <- bw.gwr(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths +\n    PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +\n    PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +\n    WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +\n    WITHIN_1KM_PRISCH,\n  data=train_data_sp,\n  approach=\"CV\",\n  kernel=\"gaussian\",\n  adaptive=TRUE,\n  longlat=FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(bw_adaptive, \"data/model/bw_adaptive.rds\")\n```\n:::\n\n\nAfter a few couple of teas, we've found optimal bandwidth is 40 neighour points. \n\n### Constructing the Adaptive Bandwidth GWR Model\n\nWe first re-load the data into R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_adaptive <- read_rds(\"data/model/bw_adaptive.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 40\n```\n\n\n:::\n:::\n\n\n\nThen we build the GWR-based hedonic pricing model using adaptive bandwidth and Gaussian kernel. Same reason as the previous step, we save a copy of the `gwrm` file.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive <- gwr.basic(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths + \n    PROX_CBD + PROX_ELDERLYCARE + \n    PROX_HAWKER + PROX_MRT + PROX_PARK + \n    PROX_MALL + PROX_SUPERMARKET +\n    WITHIN_350M_KINDERGARTEN +\n    WITHIN_350M_CHILDCARE + \n    WITHIN_350M_BUS + WITHIN_1KM_PRISCH,\n  data=train_data_sp,\n  bw=bw_adaptive, \n  kernel = 'gaussian', \n  adaptive=TRUE,\n  longlat = FALSE)\nwrite_rds(gwr_adaptive, \n          \"data/model/gwr_adaptive.rds\")\n```\n:::\n\n\n\n\n### Retrieve gwr Output Object\n\nWe re-load the saved `gwrm` object and retrieve the report of model output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive <- read_rds(\"data/model/gwr_adaptive.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-10-22 22:00:33.551728 \n   Call:\n   gwr.basic(formula = resale_price ~ floor_area_sqm + storey_order + \n    remaining_lease_mths + PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER + \n    PROX_MRT + PROX_PARK + PROX_MALL + PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN + \n    WITHIN_350M_CHILDCARE + WITHIN_350M_BUS + WITHIN_1KM_PRISCH, \n    data = train_data.sp, bw = bw_adaptive, kernel = \"gaussian\", \n    adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  resale_price\n   Independent variables:  floor_area_sqm storey_order remaining_lease_mths PROX_CBD PROX_ELDERLYCARE PROX_HAWKER PROX_MRT PROX_PARK PROX_MALL PROX_SUPERMARKET WITHIN_350M_KINDERGARTEN WITHIN_350M_CHILDCARE WITHIN_350M_BUS WITHIN_1KM_PRISCH\n   Number of data points: 10335\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n    Min      1Q  Median      3Q     Max \n-205193  -39120   -1930   36545  472355 \n\n   Coefficients:\n                              Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)              107601.073  10601.261  10.150  < 2e-16 ***\n   floor_area_sqm             2780.698     90.579  30.699  < 2e-16 ***\n   storey_order              14299.298    339.115  42.167  < 2e-16 ***\n   remaining_lease_mths        344.490      4.592  75.027  < 2e-16 ***\n   PROX_CBD                 -16930.196    201.254 -84.124  < 2e-16 ***\n   PROX_ELDERLYCARE         -14441.025    994.867 -14.516  < 2e-16 ***\n   PROX_HAWKER              -19265.648   1273.597 -15.127  < 2e-16 ***\n   PROX_MRT                 -32564.272   1744.232 -18.670  < 2e-16 ***\n   PROX_PARK                 -5712.625   1483.885  -3.850 0.000119 ***\n   PROX_MALL                -14717.388   2007.818  -7.330 2.47e-13 ***\n   PROX_SUPERMARKET         -26881.938   4189.624  -6.416 1.46e-10 ***\n   WITHIN_350M_KINDERGARTEN   8520.472    632.812  13.464  < 2e-16 ***\n   WITHIN_350M_CHILDCARE     -4510.650    354.015 -12.741  < 2e-16 ***\n   WITHIN_350M_BUS             813.493    222.574   3.655 0.000259 ***\n   WITHIN_1KM_PRISCH         -8010.834    491.512 -16.298  < 2e-16 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 61650 on 10320 degrees of freedom\n   Multiple R-squared: 0.7373\n   Adjusted R-squared: 0.737 \n   F-statistic:  2069 on 14 and 10320 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 3.922202e+13\n   Sigma(hat): 61610.08\n   AIC:  257320.2\n   AICc:  257320.3\n   BIC:  247249\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 40 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                                   Min.     1st Qu.      Median     3rd Qu.\n   Intercept                -3.2111e+08 -4.7727e+05 -8.3004e+03  5.5025e+05\n   floor_area_sqm           -2.8714e+04  1.4475e+03  2.3011e+03  3.3900e+03\n   storey_order              3.3186e+03  8.5899e+03  1.0826e+04  1.3397e+04\n   remaining_lease_mths     -1.4431e+03  2.6063e+02  3.9048e+02  5.2865e+02\n   PROX_CBD                 -1.0837e+07 -5.7697e+04 -1.3787e+04  2.6552e+04\n   PROX_ELDERLYCARE         -3.1896e+07 -4.0643e+04  1.0562e+04  6.1054e+04\n   PROX_HAWKER              -2.3985e+08 -5.1365e+04  3.0026e+03  6.4287e+04\n   PROX_MRT                 -1.1544e+07 -1.0488e+05 -4.9373e+04  5.1037e+03\n   PROX_PARK                -6.5961e+06 -4.8671e+04 -8.8128e+02  5.3498e+04\n   PROX_MALL                -1.8113e+07 -7.4238e+04 -1.3982e+04  4.9779e+04\n   PROX_SUPERMARKET         -4.5761e+06 -6.3461e+04 -1.7429e+04  3.5616e+04\n   WITHIN_350M_KINDERGARTEN -4.1638e+05 -6.0040e+03  9.0209e+01  4.7127e+03\n   WITHIN_350M_CHILDCARE    -1.0273e+05 -2.2375e+03  2.6668e+02  2.6388e+03\n   WITHIN_350M_BUS          -1.1757e+05 -1.4719e+03  1.1626e+02  1.7584e+03\n   WITHIN_1KM_PRISCH        -6.6465e+05 -5.5959e+03  2.6916e+02  5.7500e+03\n                                  Max.\n   Intercept                1.6493e+08\n   floor_area_sqm           5.0908e+04\n   storey_order             2.9537e+04\n   remaining_lease_mths     1.8119e+03\n   PROX_CBD                 2.2166e+07\n   PROX_ELDERLYCARE         8.2445e+07\n   PROX_HAWKER              5.9654e+06\n   PROX_MRT                 2.0189e+08\n   PROX_PARK                1.5072e+07\n   PROX_MALL                1.0443e+07\n   PROX_SUPERMARKET         3.8330e+06\n   WITHIN_350M_KINDERGARTEN 6.6799e+05\n   WITHIN_350M_CHILDCARE    1.0802e+05\n   WITHIN_350M_BUS          3.7313e+04\n   WITHIN_1KM_PRISCH        5.0133e+05\n   ************************Diagnostic information*************************\n   Number of data points: 10335 \n   Effective number of parameters (2trace(S) - trace(S'S)): 1730.101 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 8604.899 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 238871.8 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 237036.9 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 238209 \n   Residual sum of squares: 4.829176e+12 \n   R-square value:  0.9676571 \n   Adjusted R-square value:  0.9611535 \n\n   ***********************************************************************\n   Program stops at: 2025-10-22 22:01:48.29539 \n```\n\n\n:::\n:::\n\n\nThe report reads that R2 value has increased from 0.7373 to 0.9677 indicating model's fit has substantially proved and information loss has decresed as AICc down from 257320.3 to 238871.8.\n\n\n### Computing Adaptive Bandwidth for the Test Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_bw_test_adaptive <- bw.gwr(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths +\n    PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +\n    PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +\n    WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +\n    WITHIN_1KM_PRISCH,\n  data=test_data_sp,\n  approach=\"CV\", #   note we use approach=\"CV\" compared with bw=bw_adaptive in training\n  kernel=\"gaussian\",\n  adaptive=TRUE,\n  longlat=FALSE)\n\nwrite_rds(gwr_bw_test_adaptive, \n          \"data/model/gwr_bw_test_adaptive.rds\")\n```\n:::\n\nAfter a bit of scrolling, cross-validation determines the optimal adaptive bandwidth is **25** for the test set.\n\n###  Computing Predicted Values of the Test Data\nWe still encountered an error `inv(): matrix is singular` when computing the predictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr_pred <- gwr.predict(\n  formula = resale_price ~\n        floor_area_sqm + storey_order +\n        remaining_lease_mths + PROX_CBD + \n        PROX_ELDERLYCARE + PROX_HAWKER + \n        PROX_MRT + PROX_PARK + PROX_MALL + \n        PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +\n        WITHIN_350M_CHILDCARE + WITHIN_350M_BUS + \n        WITHIN_1KM_PRISCH, \n        data=train_data_sp, \n        predictdata = test_data_sp, \n        bw=25, \n        kernel = 'gaussian', \n        adaptive=TRUE, \n        longlat = FALSE)\nwrite_rds(gwr_pred, \n          \"data/model/gwr_pred.rds\")\n```\n:::\n\n\n\n## Calibrating Random Forest Model\n\nNext we calibrate the model by using random forest function from [ranger](https://cran.r-project.org/web/packages/ranger/index.html) package.\n\n### Preparing Coordinates Data\n\nFirst we calculate x,y coordinates matrix for whole dataset, and training and test sets, and save them on the disk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data <- read_rds(\"data/model/train_data.rds\")\ntest_data <- read_rds(\"data/model/test_data.rds\")\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(mdata)\ncoords_train <- st_coordinates(train_data)\ncoords_test <- st_coordinates(test_data)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords_train <- write_rds(coords_train, \"data/geospatial/coords_train.rds\" )\ncoords_test <- write_rds(coords_test, \"data/geospatial/coords_test.rds\" )\n```\n:::\n\n\n### Dropping Geometry Field\n\nThe geometry column should be removed since it is not required for the upcoming analysis. The code chunk below uses `st_drop_geometry()` function from the **sf** package to drop the `geometry`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain_data_nogeom <- train_data %>% st_drop_geometry()\ntest_data_nogeom <- test_data %>% st_drop_geometry()\n```\n:::\n\n\n\n###  Calibrating a Non-spatial Random Forest Model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nrf <- ranger(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths + \n    PROX_CBD + PROX_ELDERLYCARE + \n    PROX_HAWKER + PROX_MRT + PROX_PARK + \n    PROX_MALL + PROX_SUPERMARKET +\n    WITHIN_350M_KINDERGARTEN + \n    WITHIN_350M_CHILDCARE + \n    WITHIN_350M_BUS +  \n    WITHIN_1KM_PRISCH,\n  data=train_data_nogeom)\n\nrf\n```\n:::\n\nThe Ranger result shows our R2 value is 0.9496 that is much higher than non-spatial regression model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(rf, \"data/model/rf.rds\")\n```\n:::\n\n\n\n## Calibrating Geographical Weighted Random Forest Model\n\nNext we `grf()` of [SpatialML](https://cran.r-project.org/web/packages/ranger/index.html) package to calibrate a geographic random forest model.\n\n\n### Calibrating Using Training Data\n\nWe apply `grf()` of [SpatialML](https://cran.r-project.org/web/packages/ranger/index.html) package to calibrate model on training data. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\ngwRF_adaptive <- grf(\n  formula = resale_price ~ floor_area_sqm +\n    storey_order + remaining_lease_mths + \n    PROX_CBD + PROX_ELDERLYCARE + \n    PROX_HAWKER + PROX_MRT + PROX_PARK + \n    PROX_MALL + PROX_SUPERMARKET +\n    WITHIN_350M_KINDERGARTEN +\n    WITHIN_350M_CHILDCARE + \n    WITHIN_350M_BUS + WITHIN_1KM_PRISCH,\n  dframe=train_data_nogeom, \n  bw=40,\n  kernel=\"adaptive\",\n  coords=coords_train)\n```\n:::\n\nR2 on the training set is 0.9515.\n\nWe again save the new model on training data.\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(gwRF_adaptive, \"data/model/gwRF_adaptive.rds\")\n```\n:::\n\nThen we retrieve the model for next steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwRF_adaptive <- read_rds(\"data/model/gwRF_adaptive.rds\")\n```\n:::\n\n\n\n\n### Predicting by Using Test Data\n\n#### Preparing the Test Data\n\nWe use `cbind()` to combine `test_data` and `coords_test` and remove the `geometry`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_data_nogeom <- cbind(test_data, coords_test)%>%\n  st_drop_geometry()\n```\n:::\n\n  \n#### Predicting with Test Data\n\nWe use `predict.grf()` of **SpatialML** package to predict the resale price using `gwPF_adaptive` model on the test data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwRF_pred <- predict.grf(gwRF_adaptive, \n                        test_data_nogeom, \n                        x.var.name=\"X\",\n                        y.var.name=\"Y\", \n                        local.w=1,\n                        global.w=0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGRF_pred <- write_rds(gwRF_pred, \"data/model/GRF_pred.rds\")\n```\n:::\n\n\n#### Converting the Predicting Output into a data.frame\n\nWe reload the saved predicting output (generated from `predict.grf()` in the previous step) back to R and convert it into a data frame for further study since the original output is in `numeric` format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGRF_pred <- read_rds(\"data/model/GRF_pred.rds\")\nGRF_pred_df <- as.data.frame(GRF_pred)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(GRF_pred_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 5,566\nColumns: 1\n$ GRF_pred <dbl> 384349.1, 352091.0, 413359.4, 375758.8, 419446.1, 379228.8, 3…\n```\n\n\n:::\n:::\n\n\n\nTo compare the actual and predicted, we combine the with `GRF_pred_df` and select required columns: `resale_price`in `test_data` and `GRF_pred` the column where predicting outputs are in `GRF_pred_df` into a new data frame called `test_data_p` and save it on the disk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_data_p <- cbind(test_data, GRF_pred_df) %>%\n  select(resale_price, GRF_pred)\n\nglimpse(test_data_p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 5,566\nColumns: 3\n$ resale_price <dbl> 360000, 370000, 375000, 380000, 385000, 395000, 395000, 4…\n$ GRF_pred     <dbl> 384349.1, 352091.0, 413359.4, 375758.8, 419446.1, 379228.…\n$ geometry     <POINT [m]> POINT (28423.42 39745.94), POINT (30550.38 39588.77…\n```\n\n\n:::\n\n```{.r .cell-code}\nwrite_rds(test_data_p,\"data/model/test_data_p.rds\")\n```\n:::\n\n\n\n#### Calculating Root Mean Square Error\n\nTo measure the difference between actual and predicted in the regression model, we use `rmse()` of **Metrics** package to compute the Root Mean Square Error (RMSE). The RMSE is 28160.87 for this GWR model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrmse(test_data_p$resale_price, test_data_p$GRF_pred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28160.87\n```\n\n\n:::\n:::\n\n\n\n#### Visualising the Predicted Values\n\nHere, we employ a scatterplot to visualise how far the predicted values deviate from the actual ones using the functions `geom_point()` and `ggplot()`. \n\nFor the reference line, we use `geom_abline()` to create a 45-degree line in the positive quadrant by setting the arguments `slope = 1` and `intercept = 0`. To customise the line style, we can specify the `linetype` argument using numeric values or their names:\n0: blank\n1: solid (default)\n2: dashed\n3: dotted\n4: dotdash\n5: longdash\n6: twodash\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = test_data_p, aes(x= GRF_pred, y = resale_price)) +\n  geom_point() +\n geom_abline(slope = 1, intercept = 0, color = \"red\", linetype = 1, size = 0.8)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nThe general rule for evaluating model performance is that the closer the scatter points are to the diagonal line, the better the model predicts. In addition, potential outliers can be identified from the scatterplot if required, for example when points deviate significantly from the diagonal line.\n\nIn this case, we observed that most of the predicted and actual values are located close to the reference line in red.\n\n\n## Reference\n\nKam, T. S. 14 Geographically Weighted Predictive Models. R for Geospatial Data Science and Analytics. https://r4gdsa.netlify.app/chap14.html\n",
    "supporting": [
      "Hands-on_Ex08_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}