{
  "hash": "8960b7a5e4465d59dda9b6106f7313fc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"04: Spatial Weights and Applications\"\nauthor: \"Yiqiong PAN\"\ndate: \"Sep 15, 2025\"\ndate-modified: \"last-modified\"\nexecute:\n  echo: true #display the code\n  eval: true #run the code\n  message: false\n  warning: false\n  freeze: true # not render if nothing edited\neditor: visual\nformat: \n  html:\n    number-sections: true\n    number-depth: 4\n    code-link: true\n    toc: true\n---\n\n## Overview\n\nIn this exercise, we apply spatial weights in a practical implementation in R.\n\nSpatial data are rarely independent which often violates the independence assumptions of classical statistics (e.g., regression or ANOVA).Properly defining and weighting neighbours is crucial to account for spatial autocorrelation and avoid biased outcomes. Through it, we can understand who influences whom and how strong the influence is.\n\n## The Study Area and Data\n\nThe following two data sets are used here:\n\n1.  Geospatial data: Hunan county boundary layer in `shapefile` format\n\n2.  Aspatial data: `Hunan_2012.csv` for Hunan’s local development indicators in 2012.\n\n### Getting started\n\nA total of **five** R packages will be used in this exercise.\n\n| Package | Description |\n|------------------------------------|------------------------------------|\n| [sf](https://r-spatial.github.io/sf/) | Simple Features, a new R package which handles importing, managing, and processing vector-based geospatial data. |\n| [spdep](https://cran.r-project.org/web/packages/spdep/index.html) | Tools for computing spatial weights and calculating spatially lagged variables. |\n| [knitr](https://cran.r-project.org/web/packages/knitr/index.html) | Provides useful functions for dynamic document generation. |\n| [tmap](https://r-tmap.github.io/tmap/) | Creates cartographic quality static or interactive choropleth maps. |\n| [tidyverse](https://www.tidyverse.org/) | A collection of R packages for data import, cleaning, transformation, and visualisation (e.g., readr, dplyr, tidyr, ggplot2). |\n\n: {tbl-colwidths=\"\\[15,85\\]\"}\n\nAfter installation via `install.packages()`, we load them into R environment using the code below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman:: p_load(sf, spdep, knitr, tmap, tidyverse)\n```\n:::\n\n\n## Importing Data into R\n\nIn this section, we import above-mentioned two data sets into the R environment by using `st_read()` from `sf` package for geospatial data and `read_csv()` from `readr` of `tiyeverse` family.\n\n### Importing `sharefile` File\n\nThe code chunk below uses `st_read()` to import the Hunan county layer in `sharefile` format to R as an `sf` object for spatial analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\",\n                layer = \"Hunan\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `C:\\lsrgc\\ISSS626-yiqiong-pan\\Hands-on_Ex\\Hands-on_Ex04\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(hunan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 88\nColumns: 8\n$ NAME_2     <chr> \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Cha…\n$ ID_3       <int> 21098, 21100, 21101, 21102, 21103, 21104, 21109, 21110, 211…\n$ NAME_3     <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", \"L…\n$ ENGTYPE_3  <chr> \"County\", \"County\", \"County City\", \"County\", \"County\", \"Cou…\n$ Shape_Leng <dbl> 1.869074, 2.360691, 1.425620, 3.474325, 2.289506, 4.171918,…\n$ Shape_Area <dbl> 0.10056190, 0.19978745, 0.05302413, 0.18908121, 0.11450357,…\n$ County     <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", \"L…\n$ geometry   <POLYGON [°]> POLYGON ((112.0625 29.75523..., POLYGON ((112.2288 …\n```\n\n\n:::\n\n```{.r .cell-code}\ntm_shape(hunan) +\n  tm_polygons() +\n  tm_text(\"NAME_3\", size = 0.3)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n### Importing `csv` File\n\nThe code chunk uses read_csv() of `readr` to import the attribute table of local development indicators in 2012.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\nglimpse(hunan2012)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 88\nColumns: 29\n$ County      <chr> \"Anhua\", \"Anren\", \"Anxiang\", \"Baojing\", \"Chaling\", \"Changn…\n$ City        <chr> \"Yiyang\", \"Chenzhou\", \"Changde\", \"Hunan West\", \"Zhuzhou\", …\n$ avg_wage    <dbl> 30544, 28058, 31935, 30843, 31251, 28518, 54540, 28597, 33…\n$ deposite    <dbl> 10967.0, 4598.9, 5517.2, 2250.0, 8241.4, 10860.0, 24332.0,…\n$ FAI         <dbl> 6831.7, 6386.1, 3541.0, 1005.4, 6508.4, 7920.0, 33624.0, 1…\n$ Gov_Rev     <dbl> 456.72, 220.57, 243.64, 192.59, 620.19, 769.86, 5350.00, 1…\n$ Gov_Exp     <dbl> 2703.0, 1454.7, 1779.5, 1379.1, 1947.0, 2631.6, 7885.5, 11…\n$ GDP         <dbl> 13225.0, 4941.2, 12482.0, 4087.9, 11585.0, 19886.0, 88009.…\n$ GDPPC       <dbl> 14567, 12761, 23667, 14563, 20078, 24418, 88656, 10132, 17…\n$ GIO         <dbl> 9276.90, 4189.20, 5108.90, 3623.50, 9157.70, 37392.00, 513…\n$ Loan        <dbl> 3954.90, 2555.30, 2806.90, 1253.70, 4287.40, 4242.80, 4053…\n$ NIPCR       <dbl> 3528.3, 3271.8, 7693.7, 4191.3, 3887.7, 9528.0, 17070.0, 3…\n$ Bed         <dbl> 2718, 970, 1931, 927, 1449, 3605, 3310, 582, 2170, 2179, 1…\n$ Emp         <dbl> 494.310, 290.820, 336.390, 195.170, 330.290, 548.610, 670.…\n$ EmpR        <dbl> 441.4, 255.4, 270.5, 145.6, 299.0, 415.1, 452.0, 127.6, 21…\n$ EmpRT       <dbl> 338.0, 99.4, 205.9, 116.4, 154.0, 273.7, 219.4, 94.4, 174.…\n$ Pri_Stu     <dbl> 54.175, 33.171, 19.584, 19.249, 33.906, 81.831, 59.151, 18…\n$ Sec_Stu     <dbl> 32.830, 17.505, 17.819, 11.831, 20.548, 44.485, 39.685, 7.…\n$ Household   <dbl> 290.4, 104.6, 148.1, 73.2, 148.7, 211.2, 300.3, 76.1, 139.…\n$ Household_R <dbl> 234.5, 121.9, 135.4, 69.9, 139.4, 211.7, 248.4, 59.6, 110.…\n$ NOIP        <dbl> 101, 34, 53, 18, 106, 115, 214, 17, 55, 70, 44, 84, 74, 17…\n$ Pop_R       <dbl> 670.3, 243.2, 346.0, 184.1, 301.6, 448.2, 475.1, 189.6, 31…\n$ RSCG        <dbl> 5760.60, 2386.40, 3957.90, 768.04, 4009.50, 5220.40, 22604…\n$ Pop_T       <dbl> 910.8, 388.7, 528.3, 281.3, 578.4, 816.3, 998.6, 256.7, 45…\n$ Agri        <dbl> 4942.253, 2357.764, 4524.410, 1118.561, 3793.550, 6430.782…\n$ Service     <dbl> 5414.5, 3814.1, 14100.0, 541.8, 5444.0, 13074.6, 17726.6, …\n$ Disp_Inc    <dbl> 12373, 16072, 16610, 13455, 20461, 20868, 183252, 12379, 1…\n$ RORP        <dbl> 0.7359464, 0.6256753, 0.6549309, 0.6544614, 0.5214385, 0.5…\n$ ROREmp      <dbl> 0.8929619, 0.8782065, 0.8041262, 0.7460163, 0.9052651, 0.7…\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(hunan2012)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"spec_tbl_df\" \"tbl_df\"      \"tbl\"         \"data.frame\" \n```\n\n\n:::\n:::\n\n\n### Performing Relational Join\n\nThe code chunk uses `left_join()` of `dplyr` package from `tidyverse` to append the attribute table of `hunan` the spatial polygon data frame with the attribute fields of `hunan2012` data frame `by = join_by(County)` and selects required fields.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(hunan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"NAME_2\"     \"ID_3\"       \"NAME_3\"     \"ENGTYPE_3\"  \"Shape_Leng\"\n[6] \"Shape_Area\" \"County\"     \"geometry\"  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(hunan2012)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"County\"      \"City\"        \"avg_wage\"    \"deposite\"    \"FAI\"        \n [6] \"Gov_Rev\"     \"Gov_Exp\"     \"GDP\"         \"GDPPC\"       \"GIO\"        \n[11] \"Loan\"        \"NIPCR\"       \"Bed\"         \"Emp\"         \"EmpR\"       \n[16] \"EmpRT\"       \"Pri_Stu\"     \"Sec_Stu\"     \"Household\"   \"Household_R\"\n[21] \"NOIP\"        \"Pop_R\"       \"RSCG\"        \"Pop_T\"       \"Agri\"       \n[26] \"Service\"     \"Disp_Inc\"    \"RORP\"        \"ROREmp\"     \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_jn <- left_join(hunan, hunan2012) \ncolnames(hunan_jn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"NAME_2\"      \"ID_3\"        \"NAME_3\"      \"ENGTYPE_3\"   \"Shape_Leng\" \n [6] \"Shape_Area\"  \"County\"      \"City\"        \"avg_wage\"    \"deposite\"   \n[11] \"FAI\"         \"Gov_Rev\"     \"Gov_Exp\"     \"GDP\"         \"GDPPC\"      \n[16] \"GIO\"         \"Loan\"        \"NIPCR\"       \"Bed\"         \"Emp\"        \n[21] \"EmpR\"        \"EmpRT\"       \"Pri_Stu\"     \"Sec_Stu\"     \"Household\"  \n[26] \"Household_R\" \"NOIP\"        \"Pop_R\"       \"RSCG\"        \"Pop_T\"      \n[31] \"Agri\"        \"Service\"     \"Disp_Inc\"    \"RORP\"        \"ROREmp\"     \n[36] \"geometry\"   \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan<- hunan_jn %>%\n   select(1:4, 7, 15)\n\nglimpse(hunan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 88\nColumns: 7\n$ NAME_2    <chr> \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Chan…\n$ ID_3      <int> 21098, 21100, 21101, 21102, 21103, 21104, 21109, 21110, 2111…\n$ NAME_3    <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", \"Li…\n$ ENGTYPE_3 <chr> \"County\", \"County\", \"County City\", \"County\", \"County\", \"Coun…\n$ County    <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", \"Li…\n$ GDPPC     <dbl> 23667, 20981, 34592, 24473, 25554, 27137, 63118, 62202, 7066…\n$ geometry  <POLYGON [°]> POLYGON ((112.0625 29.75523..., POLYGON ((112.2288 2…\n```\n\n\n:::\n\n```{.r .cell-code}\nhunan\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 88 features and 6 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\nFirst 10 features:\n     NAME_2  ID_3    NAME_3   ENGTYPE_3    County GDPPC\n1   Changde 21098   Anxiang      County   Anxiang 23667\n2   Changde 21100   Hanshou      County   Hanshou 20981\n3   Changde 21101    Jinshi County City    Jinshi 34592\n4   Changde 21102        Li      County        Li 24473\n5   Changde 21103     Linli      County     Linli 25554\n6   Changde 21104    Shimen      County    Shimen 27137\n7  Changsha 21109   Liuyang County City   Liuyang 63118\n8  Changsha 21110 Ningxiang      County Ningxiang 62202\n9  Changsha 21111 Wangcheng      County Wangcheng 70666\n10 Chenzhou 21112     Anren      County     Anren 12761\n                         geometry\n1  POLYGON ((112.0625 29.75523...\n2  POLYGON ((112.2288 29.11684...\n3  POLYGON ((111.8927 29.6013,...\n4  POLYGON ((111.3731 29.94649...\n5  POLYGON ((111.6324 29.76288...\n6  POLYGON ((110.8825 30.11675...\n7  POLYGON ((113.9905 28.5682,...\n8  POLYGON ((112.7181 28.38299...\n9  POLYGON ((112.7914 28.52688...\n10 POLYGON ((113.1757 26.82734...\n```\n\n\n:::\n:::\n\n\n## Visualising Regional Development Indicator\n\nNext we use `tm_polygons()` to create a base map and use `qtm()` also from `tmap` to create a choropleth map to show the distribution of GDP per capita GDPPC 2012.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbasemap <- tm_shape(hunan) +\n  tm_polygons() +\n  tm_text(\"NAME_3\", size = 0.5)\n\ngdppc <- qtm(hunan, \"GDPPC\") +\n  tm_layout(\n    legend.position = c(\"left\", \"bottom\"))\ntmap_arrange(basemap, gdppc, asp = 1, ncol =2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-8-1.png){width=1344}\n:::\n:::\n\n\n::: callout-note\nQuick summary:\n\nThe side-by-side maps show that the distribution of GDP per capita (GDPPC) across Hunan Province is not evenly spread. The majority of counties record values below 60K. The darkest-shaded area is Changsha, which has the highest GDPPC, ranging from 80K to 100K, with income gradually decreasing as one moves outward from the capital circle. Outside of this core, two other counties stand out with GDPPC between 60K and 80K: Lengshuikeng, located in central Hunan, and Zixing in the southeast.\n:::\n\n## Computing Contiguity Spatial Weights\n\nNeighbours could be defined by using: Contiguity (shared border).\n\n(Insee & Eurostat, 2018) Contiguity-defined neighbourhoods are widely used in demographic and social studies. Several types of contiguity can be distinguished. In **Rook** contiguity, two neighbourhoods are considered adjacent if they share at least two common boundary points (i.e., a full edge). On the other hand, **Queen** contiguity requires only one common boundary point (e.g., an edge or a vertex). As a result, the number of neighbours defined under Queen contiguity is always greater than or equal to those defined under Rook contiguity.\n\nNext, we use `poly2nb()` of **spdep** package to calculate contiguity weights metrics for the study area `hunan`.The function allows us to specify the type of contiguity by setting the `queen` argument to either `TRUE` (Queen contiguity) or `FALSE` (Rook contiguity).\n\n:::: panel-tabset\n### (QUEEN) Contiguity Based Neighbours\n\nThe code chunk below returns **QUEEN** contiguity weight matrix.\n\nFrom the **summary statistics**, we learn that the dataset contains 88 counties, with a total of 448 neighbour connections across all regions. Among these, percentage of actual neighbour links relative to all possible links is 5.79%. On average, each county has about five neighbours.\n\nLooking at the link number distribution, we see that region ID 85 is the most connected, with 11 neighbours, while region ID 30 and 65 are the least connected, each having only one neighbour. Most counties have between four and six neighbours, which is consistent with the average of five links per region.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, queen = TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\nBy using the index code chunk below, we can print the list of neighbour ploygons for most-connected region 85.The numbers represent the polygon IDs as stored in hunan `SpatialPolygonsDataFrame` class.\n\nFurther, we can retrieve the `county name` of region 85 by looking it up in the hunan dataset, specifically using the syntax `dataset$column[i]`, which returns the corresponding value in that column.\n\nWe can also retrieve 11 neighbouring county names by using the`c()` function to concatenate the required region IDs inside the indexing operation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q[[85]] \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  1  2  3  5  6 32 56 57 69 75 78\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(wm_q[[85]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"integer\"\n```\n\n\n:::\n\n```{.r .cell-code}\nhunan$County[85]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Taoyuan\"\n```\n\n\n:::\n\n```{.r .cell-code}\nhunan$NAME_3[c(1,  2,  3,  5,  6, 32, 56, 57, 69, 75, 78)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Anxiang\"  \"Hanshou\"  \"Jinshi\"   \"Linli\"    \"Shimen\"   \"Yuanling\"\n [7] \"Anhua\"    \"Nan\"      \"Cili\"     \"Sangzhi\"  \"Taojiang\"\n```\n\n\n:::\n:::\n\n\nWe can also wrap both steps together once we get familiar with the data frames.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan$NAME_3[wm_q[[85]]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Anxiang\"  \"Hanshou\"  \"Jinshi\"   \"Linli\"    \"Shimen\"   \"Yuanling\"\n [7] \"Anhua\"    \"Nan\"      \"Cili\"     \"Sangzhi\"  \"Taojiang\"\n```\n\n\n:::\n:::\n\n\nTo simplify the code and reduce the risk of syntax errors, we can first assign the neighbour indices of a given region to a helper variable then retieve the corresponding GDPPC values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb1 <- wm_q[[1]]\nhunan$GDPPC[nb1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20981 34592 24473 21311 22879\n```\n\n\n:::\n:::\n\n\nAdditionally, we can also use the structure function `str()` to display the complete matrix.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 88\n $ : int [1:5] 2 3 4 57 85\n $ : int [1:5] 1 57 58 78 85\n $ : int [1:4] 1 4 5 85\n $ : int [1:4] 1 3 5 6\n $ : int [1:4] 3 4 6 85\n $ : int [1:5] 4 5 69 75 85\n $ : int [1:4] 67 71 74 84\n $ : int [1:7] 9 46 47 56 78 80 86\n $ : int [1:6] 8 66 68 78 84 86\n $ : int [1:8] 16 17 19 20 22 70 72 73\n $ : int [1:3] 14 17 72\n $ : int [1:5] 13 60 61 63 83\n $ : int [1:4] 12 15 60 83\n $ : int [1:3] 11 15 17\n $ : int [1:4] 13 14 17 83\n $ : int [1:5] 10 17 22 72 83\n $ : int [1:7] 10 11 14 15 16 72 83\n $ : int [1:5] 20 22 23 77 83\n $ : int [1:6] 10 20 21 73 74 86\n $ : int [1:7] 10 18 19 21 22 23 82\n $ : int [1:5] 19 20 35 82 86\n $ : int [1:5] 10 16 18 20 83\n $ : int [1:7] 18 20 38 41 77 79 82\n $ : int [1:5] 25 28 31 32 54\n $ : int [1:5] 24 28 31 33 81\n $ : int [1:4] 27 33 42 81\n $ : int [1:3] 26 29 42\n $ : int [1:5] 24 25 33 49 54\n $ : int [1:3] 27 37 42\n $ : int 33\n $ : int [1:8] 24 25 32 36 39 40 56 81\n $ : int [1:8] 24 31 50 54 55 56 75 85\n $ : int [1:5] 25 26 28 30 81\n $ : int [1:3] 36 45 80\n $ : int [1:6] 21 41 47 80 82 86\n $ : int [1:6] 31 34 40 45 56 80\n $ : int [1:4] 29 42 43 44\n $ : int [1:4] 23 44 77 79\n $ : int [1:5] 31 40 42 43 81\n $ : int [1:6] 31 36 39 43 45 79\n $ : int [1:6] 23 35 45 79 80 82\n $ : int [1:7] 26 27 29 37 39 43 81\n $ : int [1:6] 37 39 40 42 44 79\n $ : int [1:4] 37 38 43 79\n $ : int [1:6] 34 36 40 41 79 80\n $ : int [1:3] 8 47 86\n $ : int [1:5] 8 35 46 80 86\n $ : int [1:5] 50 51 52 53 55\n $ : int [1:4] 28 51 52 54\n $ : int [1:5] 32 48 52 54 55\n $ : int [1:3] 48 49 52\n $ : int [1:5] 48 49 50 51 54\n $ : int [1:3] 48 55 75\n $ : int [1:6] 24 28 32 49 50 52\n $ : int [1:5] 32 48 50 53 75\n $ : int [1:7] 8 31 32 36 78 80 85\n $ : int [1:6] 1 2 58 64 76 85\n $ : int [1:5] 2 57 68 76 78\n $ : int [1:4] 60 61 87 88\n $ : int [1:4] 12 13 59 61\n $ : int [1:7] 12 59 60 62 63 77 87\n $ : int [1:3] 61 77 87\n $ : int [1:4] 12 61 77 83\n $ : int [1:2] 57 76\n $ : int 76\n $ : int [1:5] 9 67 68 76 84\n $ : int [1:4] 7 66 76 84\n $ : int [1:5] 9 58 66 76 78\n $ : int [1:3] 6 75 85\n $ : int [1:3] 10 72 73\n $ : int [1:3] 7 73 74\n $ : int [1:5] 10 11 16 17 70\n $ : int [1:5] 10 19 70 71 74\n $ : int [1:6] 7 19 71 73 84 86\n $ : int [1:6] 6 32 53 55 69 85\n $ : int [1:7] 57 58 64 65 66 67 68\n $ : int [1:7] 18 23 38 61 62 63 83\n $ : int [1:7] 2 8 9 56 58 68 85\n $ : int [1:7] 23 38 40 41 43 44 45\n $ : int [1:8] 8 34 35 36 41 45 47 56\n $ : int [1:6] 25 26 31 33 39 42\n $ : int [1:5] 20 21 23 35 41\n $ : int [1:9] 12 13 15 16 17 18 22 63 77\n $ : int [1:6] 7 9 66 67 74 86\n $ : int [1:11] 1 2 3 5 6 32 56 57 69 75 ...\n $ : int [1:9] 8 9 19 21 35 46 47 74 84\n $ : int [1:4] 59 61 62 88\n $ : int [1:2] 59 87\n - attr(*, \"class\")= chr \"nb\"\n - attr(*, \"region.id\")= chr [1:88] \"1\" \"2\" \"3\" \"4\" ...\n - attr(*, \"call\")= language poly2nb(pl = hunan, queen = TRUE)\n - attr(*, \"type\")= chr \"queen\"\n - attr(*, \"snap\")= num 9e-08\n - attr(*, \"sym\")= logi TRUE\n - attr(*, \"ncomp\")=List of 2\n  ..$ nc     : int 1\n  ..$ comp.id: int [1:88] 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\n### (ROOK) Contiguity Based Neighbours\n\nAs mentioned earlier, the measurement type can be easily switched to **Rook** mode by disabling the `queen` argument. The code chunk below uses `poly2nb()` to compute the Rook contiguity weight matrix.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_r <- poly2nb(hunan, queen = FALSE)\nsummary(wm_r)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 440 \nPercentage nonzero weights: 5.681818 \nAverage number of links: 5 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 10 \n 2  2 12 20 21 14 11  3  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 10 links\n```\n\n\n:::\n:::\n\n\nThe summary shows that there are 88 regions in the dataset, with a total of 440 possible neighbour connections. Among these, percentage of actual neighbour links relative to all possible links is 5.68%. On average, each region has around five neighbours. Similarly, one region is the most connected, with 10 Rook neighbours, while regions 30 and 65 are the least connected, each having only one link.\n\nThe code chunk below retreives the region ID 85's neighbour names and GDPPC under ROOK.\n\nWe used the `setdiff(a, b)` function to identify the neighbours included under Queen contiguity but not under Rook. The result returned region ID **57**, named **Nan**. It is unclear whether this indicates a missing value. However, the county is located at the northeast vertex of region 85 (Taoyuan) according to the baseline map.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_r[[85]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  1  2  3  5  6 32 56 69 75 78\n```\n\n\n:::\n\n```{.r .cell-code}\nhunan$County[85]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Taoyuan\"\n```\n\n\n:::\n\n```{.r .cell-code}\nhunan$NAME_3[wm_r[[85]]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Anxiang\"  \"Hanshou\"  \"Jinshi\"   \"Linli\"    \"Shimen\"   \"Yuanling\"\n [7] \"Anhua\"    \"Cili\"     \"Sangzhi\"  \"Taojiang\"\n```\n\n\n:::\n\n```{.r .cell-code}\nhunan$GDPPC[wm_r[[85]]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 23667 20981 34592 25554 27137 24194 14567 18714 14624 19509\n```\n\n\n:::\n\n```{.r .cell-code}\nsetdiff(hunan$NAME_3[wm_q[[85]]], hunan$NAME_3[wm_r[[85]]]) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Nan\"\n```\n\n\n:::\n\n```{.r .cell-code}\nsetdiff(wm_q[[85]], wm_r[[85]]) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 57\n```\n\n\n:::\n:::\n\n\n### Prepreration for Visualisation\n\nA connectivity graph shows polygons as points and draws lines to their neighbours. To build this, we need a point for each polygon, usually the centroid.\n\nUsing `sf`, we calculate centroids, then extract longitude and latitude into two separate `numeric` objects. This is done by mapping `st_centroid` over the geometry column (`us.bound`) with `map_dbl` from purrr.\n\n-   Longitude: access with `[[1]]`\n\n-   Latitude: access with `[[2]]`\n\nThe above gives numeric vectors of coordinates for use in graph construction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlongitude <- map_dbl(hunan$geometry, ~st_centroid(.x)[[1]])\nclass(longitude)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlatitude  <- map_dbl(hunan$geometry, ~st_centroid(.x)[[2]])\n```\n:::\n\n\nNext we use `cbind()` to combine longitude and latitude and create a `matrix` object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- cbind(longitude, latitude)\n\nhead(coords)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     longitude latitude\n[1,]  112.1531 29.44362\n[2,]  112.0372 28.86489\n[3,]  111.8917 29.47107\n[4,]  111.7031 29.74499\n[5,]  111.6138 29.49258\n[6,]  111.0341 29.79863\n```\n\n\n:::\n:::\n\n\n::: callout-note\n**Syntax rules on \\[\\]**\n\n-   **Single** brackets **\\[\\]** return a sublist (still of type list).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1]  2  3  4 57 85\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(wm_q[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"list\"\n```\n\n\n:::\n:::\n\n\n-   **Double** brackets **\\[\\[ \\]\\]** return the contents of that element.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q[[1]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  2  3  4 57 85\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(wm_q[[1]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"integer\"\n```\n\n\n:::\n:::\n\n:::\n\n### Mapping QUEEN & ROOK & Comparsion\n\nThe code chunk below use plot() from base R to create two maps one for **QUEEN** contiguity based and one for **ROOK** contiguity based. It also overlays two sets of maps for **comparison**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1,2))\n\nplot(hunan$geometry, border = \"lightgrey\",\n     main = \"QUEEN Contiguity\") # countries base map\nplot(wm_q, coords, # centroid coords of each polygon\n     pch = 19, # solid circles\n     cex = 0.6, # shrinks point size to 60%\n     add = TRUE, # overlays this coords with base map\n     col = \"red\") # connecting line in red\n\n\n\nplot(hunan$geometry, border = \"lightgrey\",\n     main = \"ROOK Contiguity\") # countries base map\nplot(wm_r, coords, # centroid coords of each polygon\n     pch = 19, # solid circles\n     cex = 0.6, # shrinks point size to 60%\n     add = TRUE, # overlays this coords with base map\n     col = \"red\") # connecting line in red\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-20-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-21-1.png){width=960}\n:::\n:::\n\n\nHere we visualise `setdiff()` differences in connectivity between Queen and Rook contiguity.\n\nThe comparison map above highlights the additional **4** neighbour links (equally unidirectional 8 nonzero entries), captured by Queen in blue.\n\nThe most connected region, Taoyuan (in the north), has 11 neighbours under Queen and 10 under Rook. One corner-touching neighbour is excluded in the Rook method due to its definition. Similar differences can also be observed in the lower northeast part of the province, where Queen contiguity identifies additional vertex-based neighbours that Rook does not.\n::::\n\n## Computing Distance Based Neighbours\n\nWe could also define neighbours based on **distances** (within k kilometres). Here we use`dnearneigh()` of **spdep** package to compute distance-based weight matrices.\n\nThe function finds nearby points around a region based on straight-line distance. You can set a minimum distance (d1) and a maximum distance (d2) using the `bounds` argument.\n\nIf date is in a normal flat coordinate system (like projected x-y coordinates), it just uses Euclidean Distance.\n\nIf the coordinates are in latitude and longitude (not projected), and you set `longlat=TRUE`, the function works out distances along the Earth’s surface (great-circle distance, like the curved route a plane would fly) in kilometres, using the WGS84 Earth model.\n\n\n:::panel-tabset\n\n### Determine the Cut-off Distance\n\nThe steps show how to compute the upper distance bound.\n\n- Use `knearneigh()` from **spdep** to compute the k nearest neighbors for each point. This produces an index matrix identifying which points are the nearest neighbors of each other.\n\n::: {.cell}\n\n```{.r .cell-code}\n#coords <- st_coordinates(st_centroid(hunan)) #similar results of centroid generated in visual preparation  \n#head(coords)\nk1 <- knearneigh(coords, k=1)\nsummary(k1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Length Class  Mode   \nnn         88    -none- numeric\nnp          1    -none- numeric\nk           1    -none- numeric\ndimension   1    -none- numeric\nx         176    -none- numeric\n```\n\n\n:::\n:::\n\n- Convert the `knearneigh` object to an `nb` list (neighborhood list) with `knn2nb()`. The resulting object stores integer vectors of neighbour IDs for each region (i.e., `value` column contains region id who is the neighour of [[i]] i-th region in `hunan`).\n\n::: {.cell}\n\n```{.r .cell-code}\nk1<- knn2nb(k1)\nk1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 88 \nPercentage nonzero weights: 1.136364 \nAverage number of links: 1 \n25 disjoint connected subgraphs\nNon-symmetric neighbours list\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk1[[85]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n\n```{.r .cell-code}\nhunan$County[c(85,5)] \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Taoyuan\" \"Linli\"  \n```\n\n\n:::\n:::\n\n- Use `nbdist()` from **spdep** to calculate the lengths of the neighbour edges (distances between neighbours), expressed in kilometers (if longlat=TRUE).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk1dists <- nbdists(k1, coords, longlat = TRUE)\nhead(k1dists)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] 25.53398\n\n[[2]]\n[1] 43.03114\n\n[[3]]\n[1] 25.53398\n\n[[4]]\n[1] 29.2848\n\n[[5]]\n[1] 29.2848\n\n[[6]]\n[1] 45.98097\n```\n\n\n:::\n:::\n\n\n\n- Apply `unlist()` to flatten the list structure of the distances into a single numeric vector, so we can directly inspect or compute statistics (like the maximum distance = the upper bound).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk1dists <- unlist(k1dists)\nsummary(k1dists)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  24.79   32.57   38.01   39.07   44.52   61.79 \n```\n\n\n:::\n:::\n\nThe table above shows the largest first-nearest-neighbor distance is 61.79 km, which qualifies as the upper bound. This is because at that distance, every unit in the dataset has at least one neighbor.\n\n### Computing Fixed Distance Weight Matrix\n\nThe code chunk below uses `dnearneigh()` to compute the distance weight matrix `nb` class. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_d62 <- dnearneigh(coords, 0, 62, longlat = TRUE)\nwm_d62\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 324 \nPercentage nonzero weights: 4.183884 \nAverage number of links: 3.681818 \n```\n\n\n:::\n\n```{.r .cell-code}\nwm_d62[[85]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2 5\n```\n\n\n:::\n:::\n\n**The Summary Statistics shows across all 88 regions, there are 324 neighbouring edges and on avearge each reagion has 3.68 neighbours. **\n\nThe code chunk below can display the contents of the matrix, though the outcome is not shown here. We can also call the index of the nb list to display the neigbhours of i-th region, for example with `wm_d62[[85]]`.\n**The value entries in `wm_d62` contain the actual neighbors of the i-th region according to the neighbour distance.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(wm_d62)\n```\n:::\n\n\n\nAlternatively, we can combine `table()` and `card()` of **spdep** to display the structure of weight matrix. Tode chunk cross-tabulates each county `hunan$County` against the cardinality of its neighbor list `card(wm_d62)`, which counts how many neighbours each region has.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(table(hunan$County,card(wm_d62)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           \n            1 2 3 4 5 6\n  Anhua     1 0 0 0 0 0\n  Anren     0 0 0 1 0 0\n  Anxiang   0 0 0 0 1 0\n  Baojing   0 0 0 0 1 0\n  Chaling   0 0 1 0 0 0\n  Changning 0 0 1 0 0 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(table(hunan$County,card(wm_d62)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of cases in table: 88 \nNumber of factors: 2 \nTest for independence of all factors:\n\tChisq = 440, df = 435, p-value = 0.4241\n\tChi-squared approximation may be incorrect\n```\n\n\n:::\n:::\n\n\nThe statistics indicate there is no significant evidence that two variables (county and cardinality) are dependent. However, the results might not be reliable since the table is essential a one-hot encoding.\n\n`n.comp.nb(nb.obj)`checks connectivity in the dataset. `nc` means 1 connected component.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_comp <- n.comp.nb(wm_d62)\nn_comp$nc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n`table()` code chunk confirms all 88 counties together as a single connected component.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(n_comp$comp.id)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 1 \n88 \n```\n\n\n:::\n:::\n\n\n### Plotting Fixed Distance Weight Matrix\n\nThe code chunk below plots the distance weight matrix. The first left map shows connections based on 1st nearest neighbours while the following shows all neighbours based on cut-off boundary of 62km.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,3))\nplot(hunan$geometry, border=\"lightgrey\", main=\"1st nearest neighbours\")\nplot(k1, coords, add=TRUE, col=\"red\", length=0.08)\nplot(hunan$geometry, border=\"lightgrey\", main=\"Distance link\")\nplot(wm_d62, coords, add=TRUE, pch = 19, cex = 0.6)\nplot(hunan$geometry, border = \"lightgrey\", main = \"Distance-based Neighbours\")\nplot(wm_d62, coords,add = TRUE)\nplot(k1, coords, add = TRUE, col = \"red\", length = 0.08)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-32-1.png){width=1344}\n:::\n:::\n\n\n\n### Computing Adaptive Distance Weight Matrix\n\n\nWith a fixed distance band (e.g., 62 km), every county links to all neighbours within that radius. This contradicts modern urban geographic characteristics (heterogeneity) and may cause over-smoothing, which blurs local signals (weaker LISA extremes), inflates dependence (causing unnecessary Moran’s I), leaves sparse border/rural counties with few links, and introduces bias in models.\n\nAdaptive weights (k-nearest neighbours) are preferable when densities vary a lot, since they equalise neighbour counts and allow fairer comparison. That means every region gets exactly k neighbours, no matter if it is crowded or isolated.\n\nAsymmetric kNN is applicable for directional insights since region A may list region B among its k nearest neighbours while region B does not list A. On the other hand, enforced symmetric kNN `sym=TRUE` is better for connectivity and interpretability.\n\nWe select the smallest k that yields a connected graph and confirm robustness via sensitivity checks.\n\nRule-of-thumb: start with k∈[4,8], check connectivity, and run sensitivity (k = 4, 6, 8 …). Pick the smallest k that is connected and stable.\n\n\nThe code chunk below creates 6 non-symmtric nearest neighbours for each region. We observe nonzero links are 528 higher than preivous methods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn6 <- knn2nb(knearneigh(coords, k=6))\nknn6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 528 \nPercentage nonzero weights: 6.818182 \nAverage number of links: 6 \nNon-symmetric neighbours list\n```\n\n\n:::\n:::\n\n\n\nThe code chunk below can display the contents of the matrix, though the outcome is not shown here. We can also call the index of the nb list to display the neigbhours of i-th region, for example with `knn6[[85]]`. `summary(knn6)` confirms that no region is more or less connected than another under k-nearest neighbours. The neighbour count is fixed at six for all.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 88\n $ : int [1:6] 2 3 4 5 57 64\n $ : int [1:6] 1 3 57 58 78 85\n $ : int [1:6] 1 2 4 5 57 85\n $ : int [1:6] 1 3 5 6 69 85\n $ : int [1:6] 1 3 4 6 69 85\n $ : int [1:6] 3 4 5 69 75 85\n $ : int [1:6] 9 66 67 71 74 84\n $ : int [1:6] 9 46 47 78 80 86\n $ : int [1:6] 8 46 66 68 84 86\n $ : int [1:6] 16 19 22 70 72 73\n $ : int [1:6] 10 14 16 17 70 72\n $ : int [1:6] 13 15 60 61 63 83\n $ : int [1:6] 12 15 60 61 63 83\n $ : int [1:6] 11 15 16 17 72 83\n $ : int [1:6] 12 13 14 17 60 83\n $ : int [1:6] 10 11 17 22 72 83\n $ : int [1:6] 10 11 14 16 72 83\n $ : int [1:6] 20 22 23 63 77 83\n $ : int [1:6] 10 20 21 73 74 82\n $ : int [1:6] 18 19 21 22 23 82\n $ : int [1:6] 19 20 35 74 82 86\n $ : int [1:6] 10 16 18 19 20 83\n $ : int [1:6] 18 20 41 77 79 82\n $ : int [1:6] 25 28 31 52 54 81\n $ : int [1:6] 24 28 31 33 54 81\n $ : int [1:6] 25 27 29 33 42 81\n $ : int [1:6] 26 29 30 37 42 81\n $ : int [1:6] 24 25 33 49 52 54\n $ : int [1:6] 26 27 37 42 43 81\n $ : int [1:6] 26 27 28 33 49 81\n $ : int [1:6] 24 25 36 39 40 54\n $ : int [1:6] 24 31 50 54 55 56\n $ : int [1:6] 25 26 28 30 49 81\n $ : int [1:6] 36 40 41 45 56 80\n $ : int [1:6] 21 41 46 47 80 82\n $ : int [1:6] 31 34 40 45 56 80\n $ : int [1:6] 26 27 29 42 43 44\n $ : int [1:6] 23 43 44 62 77 79\n $ : int [1:6] 25 40 42 43 44 81\n $ : int [1:6] 31 36 39 43 45 79\n $ : int [1:6] 23 35 45 79 80 82\n $ : int [1:6] 26 27 37 39 43 81\n $ : int [1:6] 37 39 40 42 44 79\n $ : int [1:6] 37 38 39 42 43 79\n $ : int [1:6] 34 36 40 41 79 80\n $ : int [1:6] 8 9 35 47 78 86\n $ : int [1:6] 8 21 35 46 80 86\n $ : int [1:6] 49 50 51 52 53 55\n $ : int [1:6] 28 33 48 51 52 54\n $ : int [1:6] 32 48 51 52 54 55\n $ : int [1:6] 28 48 49 50 52 54\n $ : int [1:6] 28 48 49 50 51 54\n $ : int [1:6] 48 50 51 52 55 75\n $ : int [1:6] 24 28 49 50 51 52\n $ : int [1:6] 32 48 50 52 53 75\n $ : int [1:6] 32 34 36 78 80 85\n $ : int [1:6] 1 2 3 58 64 68\n $ : int [1:6] 2 57 64 66 68 78\n $ : int [1:6] 12 13 60 61 87 88\n $ : int [1:6] 12 13 59 61 63 87\n $ : int [1:6] 12 13 60 62 63 87\n $ : int [1:6] 12 38 61 63 77 87\n $ : int [1:6] 12 18 60 61 62 83\n $ : int [1:6] 1 3 57 58 68 76\n $ : int [1:6] 58 64 66 67 68 76\n $ : int [1:6] 9 58 67 68 76 84\n $ : int [1:6] 7 65 66 68 76 84\n $ : int [1:6] 9 57 58 66 78 84\n $ : int [1:6] 4 5 6 32 75 85\n $ : int [1:6] 10 16 19 22 72 73\n $ : int [1:6] 7 19 73 74 84 86\n $ : int [1:6] 10 11 14 16 17 70\n $ : int [1:6] 10 19 21 70 71 74\n $ : int [1:6] 19 21 71 73 84 86\n $ : int [1:6] 6 32 50 53 55 69\n $ : int [1:6] 58 64 65 66 67 68\n $ : int [1:6] 18 23 38 61 62 63\n $ : int [1:6] 2 8 9 46 58 68\n $ : int [1:6] 38 40 41 43 44 45\n $ : int [1:6] 34 35 36 41 45 47\n $ : int [1:6] 25 26 28 33 39 42\n $ : int [1:6] 19 20 21 23 35 41\n $ : int [1:6] 12 13 15 16 22 63\n $ : int [1:6] 7 9 66 68 71 74\n $ : int [1:6] 2 3 4 5 56 69\n $ : int [1:6] 8 9 21 46 47 74\n $ : int [1:6] 59 60 61 62 63 88\n $ : int [1:6] 59 60 61 62 63 87\n - attr(*, \"region.id\")= chr [1:88] \"1\" \"2\" \"3\" \"4\" ...\n - attr(*, \"call\")= language knearneigh(x = coords, k = 6)\n - attr(*, \"sym\")= logi FALSE\n - attr(*, \"type\")= chr \"knn\"\n - attr(*, \"knn-k\")= num 6\n - attr(*, \"class\")= chr \"nb\"\n - attr(*, \"ncomp\")=List of 2\n  ..$ nc     : int 1\n  ..$ comp.id: int [1:88] 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn6[[85]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  2  3  4  5 56 69\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(knn6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 528 \nPercentage nonzero weights: 6.818182 \nAverage number of links: 6 \nNon-symmetric neighbours list\nLink number distribution:\n\n 6 \n88 \n88 least connected regions:\n1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 with 6 links\n88 most connected regions:\n1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 with 6 links\n```\n\n\n:::\n:::\n\n\nAlternatively, we can check the table of cardinality per region using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(table(hunan$County, card(knn6)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           \n            6\n  Anhua     1\n  Anren     1\n  Anxiang   1\n  Baojing   1\n  Chaling   1\n  Changning 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(table(hunan$County, card(knn6)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of cases in table: 88 \nNumber of factors: 2 \nTest for independence of all factors:\n\tChisq = 0, df = 0, p-value = 1\n\tChi-squared approximation may be incorrect\n```\n\n\n:::\n:::\n\n\n\n### Ploting Adaptive Distance Based Neighours\n\nThe code chunk below plots the adaptive weights matrix.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#first the ploygons\nplot(hunan$geometry, border = \"lightgrey\", main = \"6-nearest Neighbours (Distance Based)\")\n# then add the connections\nplot(knn6, coords, add = TRUE, col = \"red\", cex = 0.6, pch = 19)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex04_files/figure-html/unnamed-chunk-37-1.png){width=960}\n:::\n:::\n\n\n:::callout-note\n\n**Plotting Guide: **\n\n- `pch` = plotting character (the marker shape) for the node points drawing at each centroid.\n\nCommon codes: `1` open circle, `16/19` solid circle (`19` is a larger solid dot), `15` solid square, `17` solid triangle, `0–25` are predefined shapes.\n\nFor pch `21–25` you can also set `bg` (fill color) in addition to `col` (border).\n\n- `cex` = character expansion (size scale) for the markers (and text, when used with text).\n\n`cex = 1` is default; `0.6` makes the dots smaller; `1.5` would make them larger.\n\n- Lines (connections) are controlled separately:\n\n`col`: line color,\n\n`lwd`: line width,\n\n`lty`: line type (solid, dashed, etc.).\n\n- Directed kNN extras (if plotting asymmetric kNN):\n\n`arrows = TRUE` adds arrowheads,\n\n`length` controls arrowhead length (e.g., `length = 0.08`), not point size.\n\n:::\n\n\n:::\n\n\n## Weights Based on IDW (Inversed Distance Method)\n\nIn this section we compute a spatial weigh matrix with Inversed Distance Method (IDW) based on QUEEN Contiguity based matrix.\n\nThe code chunk below uses ``nbdists()` from **spdep** (spatial dependence) package compute distances between areas. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist <- nbdists(wm_q, coords, longlat = TRUE)\nhead(dist,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] 65.12941 25.53398 54.91802 35.61352 87.32760\n\n[[2]]\n[1] 65.12941 56.67944 51.92312 43.03114 58.16151\n\n[[3]]\n[1] 25.53398 35.43536 27.05778 71.64530\n```\n\n\n:::\n\n```{.r .cell-code}\nids <- lapply(dist, function(x) 1/(x))\nhead(ids,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] 0.01535405 0.03916350 0.01820896 0.02807922 0.01145113\n\n[[2]]\n[1] 0.01535405 0.01764308 0.01925924 0.02323898 0.01719350\n\n[[3]]\n[1] 0.03916350 0.02822040 0.03695795 0.01395765\n```\n\n\n:::\n:::\n\n\n::: callout-note\n\n**built-in R lambda functions (Statology, n.d.)**\n\n- apply(X, MARGIN, FUN): X is the name of the matrix or data frame\n\n- lapply(X, FUN) : X is the name of the list, vector, or data frame\n\n- sapply(X, FUN): returns a vector instead of a list (could return a list depending on vector length)\n\n- tapply(X, INDEX, FUN): X is the name of the object, typically a vector\n\n- FUN is the specific operation you want to perform (e.g. min, max, sum, mean, etc.)\n\n:::\n\n\n## Row-standardised Weights Matrix\n\nEach neighbouring polygon is assigned an equal weight (style=\"W\"), calculated as 1/ number of neighbors.\n\nThe weighted income values are then summed. \n\nThis simple approach can bias results for edge polygons, which have fewer neighbours and may distort spatial autocorrelation.\n\nFor this example, we use style=\"W\" for simplicity, though more robust alternatives like style=\"B\" (Binary (1/0) are available.\n\nThe code chunk uses `nb2listw()` to turn neighbour list `wm_q` matrix to into weights object. `zero.policy = TRUE` assigns 0 weights to island (zero link) and avoid errors.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, style = \"W\", zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n:::\n\n\nThere are three columns in `rswm_q` (class `listw`): `style`, `neighbours` and `weights`. Summary of `neighbouts` shows the distribution of number of neighours. For example, the most connected region is ID 85. The `weights` column stores equal weights based on the number of neighbours. For instance, region 85 has 11 links, so each neighbour of 85 is assigned a weight of 1/11 (adjacency decay).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(rswm_q$neighbours)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(rswm_q$weights,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] 0.2 0.2 0.2 0.2 0.2\n\n[[2]]\n[1] 0.2 0.2 0.2 0.2 0.2\n\n[[3]]\n[1] 0.25 0.25 0.25 0.25\n```\n\n\n:::\n\n```{.r .cell-code}\nrswm_q$weights[85]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n [1] 0.09090909 0.09090909 0.09090909 0.09090909 0.09090909 0.09090909\n [7] 0.09090909 0.09090909 0.09090909 0.09090909 0.09090909\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(unlist(rswm_q$weights))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n0.09091 0.14286 0.20000 0.19643 0.20000 1.00000 \n```\n\n\n:::\n:::\n\n\n\n\nTO demonstrate the difference, the code chunk below calls `style = B` and uses previously created IDW distance decay `ids` (closer neighbours carry more weight) to create Inverse Distance Weights matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_ids <- nb2listw(wm_q, glist=ids, style=\"B\", zero.policy=TRUE)\nrswm_ids\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: B \nWeights constants summary:\n   n   nn       S0        S1     S2\nB 88 7744 8.786867 0.3776535 3.8137\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(rswm_ids$neighbours)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(rswm_ids$weights,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] 0.01535405 0.03916350 0.01820896 0.02807922 0.01145113\n\n[[2]]\n[1] 0.01535405 0.01764308 0.01925924 0.02323898 0.01719350\n\n[[3]]\n[1] 0.03916350 0.02822040 0.03695795 0.01395765\n```\n\n\n:::\n\n```{.r .cell-code}\nrswm_ids$weights[85]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n [1] 0.011451133 0.017193502 0.013957649 0.016183544 0.009810297 0.010656545\n [7] 0.013416965 0.009903702 0.014199260 0.008217581 0.011407794\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(rswm_q$neighbours[[85]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(rswm_q$weights[[85]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(unlist(rswm_ids$weights))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n0.008218 0.015088 0.018739 0.019614 0.022823 0.040338 \n```\n\n\n:::\n:::\n\n\n::: callout- note\n\nHere are a few combinations for weighting neighbours  \n\n- Equal neighbour weights (row-standardised):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q<- nb2listw(wm_q, style = \"W\", zero.policy = TRUE)  # no glist\nsummary(rswm_q$neighbours)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(unlist(rswm_q$weights))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n0.09091 0.14286 0.20000 0.19643 0.20000 1.00000 \n```\n\n\n:::\n:::\n\n\n\n- IDW, unstandardised (raw 1/d):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_ids <- nb2listw(wm_q, glist = ids, style = \"B\", zero.policy = TRUE)\nsummary(rswm_ids$neighbours)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(unlist(rswm_ids$weights))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n0.008218 0.015088 0.018739 0.019614 0.022823 0.040338 \n```\n\n\n:::\n:::\n\n\n\n- IDW, row-standardised (sums to 1 per row):\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_ids_W <- nb2listw(wm_q, glist = ids, style = \"W\", zero.policy = TRUE)\nsummary(rswm_ids_W$neighbours)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(unlist(rswm_ids_W$weights))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n0.05894 0.13342 0.17603 0.19643 0.23961 1.00000 \n```\n\n\n:::\n:::\n\n\n- Pure binary adjacency (0/1):\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_bin <- nb2listw(wm_q, style = \"B\", zero.policy = TRUE) \nsummary(rswm_bin$neighbours)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(unlist(rswm_bin$weights))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      1       1       1       1       1       1 \n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n## Application of Spatial Weight Matrix\n\n\n\n\n\nWe define the neighbours (who influences whom) using: Contiguity(shared border), Distance(within k kilometres), Trajectory: order or flow.\n\nWe weight the neighbours (how strong the influence is) using: Binary (1/0), Distance decay (closer neighbours carry more weight), Strength-based (combined measures, such as shared boundary length, population, or flows).\n\n## Reference\n\nKam, T. S. 8 Spatial Weights and Applications. R for Geospatial Data Science and Analytics. https://r4gdsa.netlify.app/chap08\n\nInsee, & Eurostat. (2018, October). Handbook of spatial analysis: Theory and application with R (V. Loonis, Dir.; M.-P. de Bellefon, Coord.; Insee Méthodes, No. 131). Insee. https://www.insee.fr/en/information/3635545\n\nStatology. (n.d.). A guide to apply, lapply, sapply, and tapply in R. Statology. Retrieved September 19, 2025, from https://www.statology.org/a-guide-to-apply-lapply-sapply-and-tapply-in-r/\n",
    "supporting": [
      "Hands-on_Ex04_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}